### ISSUE TITLE
an example of a "complete" rfc822 meta data file

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#1457]
Hi @mih ,

continuing on our brief discussion -- I could try to come up with some `metadata-edit` command which could be used to help to enter/change dataset-level metadata, but I would really appreciate if you (as the visioner/author of rfc822 and all of the metadatas) could provide me with a good example.  Also, if we go with rfc822 as our default metadata format, we would need to decide on actual details of fields specification (e.g. adhere to format of terms used by some other format(s)?) or not to care about them at all, which would limit its usability.  E.g. for rfc822 I envision smth like

```yaml
## Enter or modify meta data for the dataset by modifying this file.
## Lines which start with ## are considered to be internal copies and removed
## when file actually gets saved.
## Many fields could have short value on the same line as the field name
## followed by more text in the lines which follow it, but indented.  Multiple
## paragraphs could be separated with a line containing a single dot (.)
##
## A short one "word" descriptive name of the dataset, e.g.
## Name:  fingertapping
Name: 
## A one line description of the dataset, e.g.
## Title: Neuroimaging (fMRI) study of basic motor responses invoked by moving tentacles of the upper limbs
Title:
## Year(s) and the owner (ideally with contact information) the copyright of this work
## (if/when copyright applies).  Multiple entries could be provided in multiple lines, e.g.
## Copyright: 2015-2017, DataLad Team <team@datalad.org>
##                    2016, Sharktopus <sharktopus@example.com>
Copyright:
## License for the dataset, with brief name in the first line and if needed detailed text
## in the following paragraph, e.g.
## License: ODC-PDDL-1.0
##     ODC Public Domain Dedication and License.  You are free to share, create and adapt.
##    .
##     Full text of the license: http://opendatacommons.org/licenses/pddl/
License:

```
and so on.
question/concern (as I was typing it):  
- how to enter multiple licenses (as you know -- could happen quite easily, e.g. consider having data and code within the same dataset), i.e. should we allow for the same field to be repeated (I don't think rfc822 allows for that) and take that into account when aggregating (which I am not fluent in yet even without touching any file-level based metadata ;))?
- is there any "standard" syntax highlighter for common editors (e.g. vim, emacs) for this data format?
- yet to figure out the easiest/most efficient way to auto-format it in Python happen I have a dictionary...  I know that rfc822 is what used by mail clients but not sure if we are talking about pure 822 with e.g. '.' for paragraph separation as was adopted for debian/control which I do not think even part of rfc822... so somewhere we should formalize all of that
