### ISSUE TITLE
DOC+TST: Use-cases driven/inspired documentation/testing/development

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#3229]
Echoing our "development oriented" discussion today (thanks @mih and @kyleam) on how possibly we could/should make the development workflow better (via e.g. code restructuring #3192 etc), I have decided to bring up discussion on how we could possibly make it easier to learn to use DataLad, discover what it offers, and potentially reduce pains when API goes through changes.  High level goal is to be able to have answers to common questions on "How to do X" at different levels (multi-command workflows  and single command invocations), while also providing some assurance that the answers are correct and somewhat optimal.

This issue is to discuss possible ways on how we could harmonize presentation and assurance (testing) of fulfilling a set of specific use cases.  So it goes well inline with solidifying our "core" in terms of functionality, not necessarily in rigidness of API. I am quite often asked as question on "how to do this with datalad" answer to which requires either a single or a few commands, and then even for a single command (e.g. `create-sibling-github`) I end up pointing to a screencast from [DataLad Features](https://www.datalad.org/features), which typically does more and/or not exactly what is asked for, or simply no longer works that way.

So how could we improve this situation?

# "Status Quo" 

### High-level elaborate use cases

We present in a variety of places:
- [Data Management use cases](http://docs.datalad.org/en/latest/usecases/index.html) in the docs
  - Basic provenance tracking - rendered from a `docs/casts/simple_provenance_tracking.sh`
  - A typical collaborative data management workflow - seems to come from `docs/examples/3rdparty_analysis_workflow.sh` (related - #2266, pointing that it is likely an outdated one) .
- [DataLad Features](https://www.datalad.org/features) on the main website.  Largely (if not completely) coming from `docs/casts/`.

#### Testing

`docs/examples/3rdparty_analysis_workflow.sh` is though an outdated one, probably is the only one which is automatically tested in every matrix run of travis (takes about 20 sec).  AFAIK we do not test cast scripts, so those go stale and website does not reflect currently optimal or even valid way to do things (see e.g. https://github.com/datalad/datalad.org/issues/46, https://github.com/datalad/datalad.org/issues/45).

## One-command invocation use cases

We simply do not have them documented or itemized. It is assumed that `--help` (often providing a mouthful of well documented options), is sufficient to figure out how to do things.  But as could be discovered from aforementioned high level use case examples, in many real use cases correct command line specification is not trivial.   
The closest to a documentation of how to do X with a command Y was AFAIK elaborated for `get`/`install` unification and set in digital tomb of a [google spreadsheet](https://docs.google.com/spreadsheets/d/1bi3AQK5yMKwTA_6FN1oCPnIGASy9VmN8LbARr15XMKE/edit?usp=sharing), and thus probably does no longer reflect reality.

### Testing

Many of those use cases are tested by the "unit" (or some which are tagged as "integration") tests, but it is not necessarily clear which use case any given unittest is testing.  At best we are pointing to a github issue which inspired a fix we needed to fulfill a specific use case.  I hoped to find some mentioning of `UC` we had elaborated for `install/get` but it seems that we didn't really care to reference them.

## Exercises/Tutorials

Although could be considered "orthogonal", might be implemented as related.  Relevant idea was voiced awhile back in https://github.com/datalad/datalad.org/issues/45 . ATM the best exercises are the ones prepared for the ReproNim training workshops, e.g.
- [very basic DataLad install/explore](http://www.repronim.org/sfn2018-training/02-02-distros/#datalad)
- [ReproIn using datalad-containers](http://www.repronim.org/sfn2018-training/04-02-reproin/)
- [GLM using run/datalad-containers/rerun](http://www.repronim.org/sfn2018-training/04-03-reproin_glm/)

### Testing

Those are ReproNim ones are well tested right before the workshop, but even then it often becomes not so clear on details of how needed computational environments came about etc (see e.g. https://github.com/ReproNim/sfn2018-training/issues/24)

# Proposal: Use-cases "library"

A data structure which would either list the precise code/invocation snippets and/or point to external scripts, so that each use case could be smoke-tested automagically but also could just come accompanied with a more extended unittest, or just mentioned (tag?) in the test. E.g. based on that `install/get` spreadsheet we could have (took identifier as is for UC1 and random one for the elaborate one - we can come up with more meaningful scheme)

```yaml
UC1:
 - purpose: Install a dataset from a URL without installing any subdatasets
 - cmdline:
   - commands:
     - datalad install -s URL
     - datalad install URL
   - returns: # prints in cmdline
     - status record if `install` actually installed a dataset.  
     - nothing if the dataset at the target path already exists (apparently). 
   - errors:
     - if target path contains a dataset from another URL
 - python:
   - install(source=URL)
```
yet not sure if listing of returns is valuable since they are common across many use-cases, but here we might even take shortcuts of yaml and describe them, but anyhow wouldn't be able to validate their correctness.

```yaml
UC55:
 - purpose: Create a new dataset in a given directory, with git-annex instructed to commit text files directly to git
 - cmdline:
   - commands:
     - datalad create --text-no-annex PATH
     - datalad create -d PATH --text-no-annex
     - datalad --proc-post cfg_text2git --cmd rev-create -d PATH
 ...
```

For the above one I even thought to add a section like
```yaml
- cmdline:
  - incorrect_commands:
    - command: datalad --proc-post cfg_text2git --cmd rev-create PATH
      rationale: Procedures need to know the dataset ahead of time. See https://github.com/datalad/datalad/issues/2732 for more info
```
which could be tested to be the expected "by design" failure.

and even just point to casts:
```yaml
UC999:
 - cast: docs/casts/basic_search.sh
```
where `purpose` could be picked up from the `full_title` of the cast or just duplicated here.

Replacing placeholders such as URL and PATH in aforementioned examples would provide ready to be used invocations for smoke testing in case of cmdline and python.  For cast scripts there might be more to be done, especially for those which would need messing around with external resources such as GitHub to make them runnable, but IMHO there is nothing to be not possible.  Any use case could be accompanied with a more elaborate `test_UCXXX_1` etc to unittest its functioning further.  Could even be a `@usecase('UCXXX')` decorator which would pass the output of running that python code as an argument to the test function for further interrogation after smoke testing is "finished".  It would sweep through multiple invocations if multiple choices to do the same thing were specified.

Adding some tags or grouping use cases by purpose (often luckily corresponding to the command) would allow to present them in a single (or multiple, e.g. tagged as `web` to be picked up for the main website) location... There could even be "datalad helpme" which would do a simple search (we have whoosh as a dependency after all already) on purposes/descriptions possibly finding the answer -- example -- for their question.

But the main goal here is to provide a human and machine readable listing of obviously **not for all, but the "core"** most commonly used use cases which we want to address, and keep "stable" or somehow annotated (e.g. be able to point per command up to which, or from which version it is a legit invocation or output)

Please chime in.  May be it would not scale, or would not be as valuable as I think it would.
