### ISSUE TITLE
git-annex no longer provides remote name with GETCONFIG name

### ISSUE THREAD

**Issue by mih** [datalad/datalad#4259]
In the ria special remote implementation we are using AnnexRemote with

```
name = self.annex.getconfig('name')
```
to issue a `GETCONFIG name` request to to git-annex.

This used to give the `name` of the special remote as given to `git annex initremote`, and is confirmed to work as of git-annex 7.20191230.

With git-annex 8.20200226 the response to this request (while `git annex initremote` is driving the special remote) is empty. This breaks our special remote, as it needs the name to look up additional configuration.

@joeyh was this an intentional change? I could not locate related topic on the git-annex changelog other than the introduction of LISTCONFIGS -- which should not break prior behavior, as far as I can see.

**Comment by joeyh** [comment]
This change was part of the remote config parsing. It now separates
the configs used by the special remote with ones used by git-annex
itself.

I had not considered that they may look at their name or other configs
like that. Will need to revisit that change. Could you please file a
bug report?

-- 
see shy jo

**Comment by mih** [comment]
Done, thx!

https://git-annex.branchable.com/bugs/git-annex_no_longer_provides_remote_name_with_GETCONFIG_name

**Comment by mih** [comment]
Fixed, thx @joeyh !

https://git-annex.branchable.com/bugs/git-annex_no_longer_provides_remote_name_with_GETCONFIG_name/#comment-12a9c26a4f22d0e792058ed48f6c2e52

**Comment by aqw** [comment]
@bpoldrack pointed me in the direction of this issue (and looks similar to #4509). If it's the wrong one, please let me know, and I will deflect all blame to him. ;-)

I seem to have re-encountered this bug with version `8.20201127`

```
mkdir watch_it_burn
cd watch_it_burn
datalad create .
datalad create -d . www
cd www
datalad create-sibling-ria -r --name inm7 --storage-name "inm7-ssh" "ria+ssh://debian_inm7.ds.inm7.de/ds/debian_inm7/srv"
git annex initremote inm7-ro url="ria+https://debian_inm7.ds.inm7.de" autoenable=true encryption=none externaltype=ora type=external --sameas inm7-ssh
```

(I don't pass `archive-id` to the `initremote` to avoid a second bug, which @bpoldrack is fixing as we speak.)

<details><summary>datalad wtf</summary>
<p>

```
❱ datalad wtf
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## datalad 
  - full_version: 0.13.7
  - version: 0.13.7
## dataset 
  - id: d725c883-4174-4d23-9439-0ce4120f32ae
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /home/aqw/git/inm7/debian_inm7/www
  - repo: AnnexRepo
## dependencies 
  - annexremote: 1.4.5
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 8.20201127
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.30.0
  - cmd:system-git: 2.30.0
  - cmd:system-ssh: 8.4p1
  - humanize: 3.2.0
  - iso8601: 0.1.13
  - keyring: 21.8.0
  - keyrings.alt: UNKNOWN
  - msgpack: 1.0.2
  - requests: 2.25.1
  - tqdm: 4.56.0
  - wrapt: 1.12.1
## environment 
  - LANG: en_US.UTF-8
  - LANGUAGE: en_US.UTF-8
  - LC_ALL: en_US.UTF-8
  - LC_CTYPE: en_US.UTF-8
  - PATH: /home/aqw/.venvs/datalad/bin:/home/aqw/.dotfiles/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin:/usr/local/games:/usr/games
## extensions 
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.26
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.8.4
    - http-client-0.6.4.1
    - persistent-sqlite-2.10.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.1.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 8
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20201127
## location 
  - path: /home/aqw/git/inm7/debian_inm7/www
  - type: dataset
## metadata_extractors 
  - annex: 
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio: 
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - datacite: 
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822: 
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif: 
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage: 
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image: 
    - load_error: No module named 'PIL' [image.py:<module>:16]
    - module: datalad.metadata.extractors.image
  - xmp: 
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## python 
  - implementation: CPython
  - version: 3.9.1+
## system 
  - distribution: debian/unstable/sid
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 290
  - name: Linux
  - release: 5.7.0-1-amd64
  - type: posix
  - version: #1 SMP Debian 5.7.6-1 (2020-06-24)
```
</p>
</details>
