### ISSUE TITLE
datalad get (and git-annex get) report "ok" on windows but the file is still a git link

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#4678]
@mvdm , encouraged by the success of @manimoh (with rclone special remote and dropbox), ventured into the land of trying DataLad on Windows. 

This is in the dataset from http://datasets.datalad.org/?dir=/labs/mvdm/BiconditionalOdor , you can see that upon `get` the file is still a git link

```shell
(py37) PS C:\Users\mvdm\BiconditionalOdor\M040-2020-04-28-CDOD11> datalad get .\M040-2020-04-28-4.2mm-L6-pre_17minsin.png
get(ok): M040-2020-04-28-CDOD11\M040-2020-04-28-4.2mm-L6-pre_17minsin.png (file) [from origin...]
(py37) PS C:\Users\mvdm\BiconditionalOdor\M040-2020-04-28-CDOD11> cat .\M040-2020-04-28-4.2mm-L6-pre_17minsin.png
/annex/objects/MD5E-s846290--cb1db09d32f84c87fde6accfaf5f415e.png
```

<details>
<summary>DataLad WTF</summary> 

# WTF
## datalad
  - full_version: 0.13.0
  - version: 0.13.0
## dataset
  - id: f4bba2f8-a9d2-11ea-a6f2-002590f97d84
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: C:\Users\mvdm\BiconditionalOdor
  - repo: AnnexRepo
## dependencies
  - annexremote: 1.4.3
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:annex: 8.20200331-gb11931a4a
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.23.0.windows.1
  - cmd😒ystem-git: 2.23.0.windows.1
  - cmd😒ystem-ssh: 8.0p1
  - humanize: 2.5.0
  - iso8601: 0.1.12
  - keyring: 21.2.1
  - keyrings.alt: 3.4.0
  - msgpack: 1.0.0
  - requests: 2.24.0
  - tqdm: 4.47.0
  - wrapt: 1.12.1
## environment
  - PATH: C:\Users\mvdm\miniconda3\envs\py37;C:\Users\mvdm\miniconda3\envs\py37\Library\mingw-w64\bin;C:\Users\mvdm\miniconda3\envs\py37\Library\usr\bin;C:\Users\mvdm\miniconda3\envs\py37\Library\bin;C:\Users\mvdm\miniconda3\envs\py37\Scripts;C:\Users\mvdm\miniconda3\envs\py37\bin;C:\Users\mvdm\miniconda3\condabin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\MATLAB\R2018a\bin;C:\Program Files\MiKTeX 2.9\miktex\bin\x64;C:\WINDOWS\System32\OpenSSH;C:\Program Files\PuTTY;C:\Program Files\Git\cmd;C:\Ruby23-x64\bin;C:\Users\mvdm\AppData\Local\Microsoft\WindowsApps;C:\Program Files (x86)\Graphviz2.38\bin;C:\Program Files\gs\gs9.20\bin;.
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - TorrentParser
    - Feeds
    - Testsuite
  - dependency versions:
    - aws-0.21.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.4
    - feed-1.2.0.1
    - ghc-8.6.5
    - http-client-0.6.4
    - persistent-sqlite-2.9.3
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0.1
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - local repository version: 8
  - operating system: mingw32 x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions:
    - 8
  - upgrade supported from repository versions:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20200331-gb11931a4a
## location
  - path: C:\Users\mvdm\BiconditionalOdor
  - type: dataset
## metadata_extractors
  - annex:
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio:
    - load_error: No module named 'mutagen' [
audio.py
:<module>:17]
    - module: 
datalad.metadata.extractors.audio

  - datacite:
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core:
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822:
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif:
    - load_error: No module named 'exifread' [
exif.py
:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage:
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image:
    - load_error: No module named 'PIL' [
image.py
:<module>:16]
    - module: datalad.metadata.extractors.image
  - xmp:
    - load_error: No module named 'libxmp' [
xmp.py
:<module>:20]
    - module: datalad.metadata.extractors.xmp
## python
  - implementation: CPython
  - version: 3.7.7
## system
  - distribution:   10/10.0.17134/SP0
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: cp1252
  - max_path_length: 259
  - name: Windows
  - release: 10
  - type: nt
  - version: 10.0.17134
</details>

Surprising fact that it worked ok for @manimoh

**Comment by yarikoptic** [comment]
@manimoh, could you please post output from your run of `datalad wtf` on the box where `get` works properly

**Comment by manimoh** [comment]
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## datalad
  - full_version: 0.12.7
  - version: 0.12.7
## dataset
  - id: None
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: D:\data-formats
  - repo: GitRepo
## dependencies
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:annex: 8.20200331-gb11931a4a
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.27.0.windows.1
  - cmd:system-git: 2.27.0.windows.1
  - cmd:system-ssh: 8.3p1
  - git: 3.1.3
  - gitdb: 4.0.5
  - humanize: 2.4.0
  - iso8601: 0.1.12
  - keyring: 21.2.1
  - keyrings.alt: 3.4.0
  - msgpack: 1.0.0
  - requests: 2.24.0
  - tqdm: 4.46.1
  - wrapt: 1.12.1
## environment
  - PATH: C:\Users\mvdmlab\miniconda3;C:\Users\mvdmlab\miniconda3\Library\mingw-w64\bin;C:\Users\mvdmlab\miniconda3\Library\usr\bin;C:\Users\mvdmlab\miniconda3\Library\bin;C:\Users\mvdmlab\miniconda3\Scripts;C:\Users\mvdmlab\miniconda3\bin;C:\Users\mvdmlab\miniconda3\condabin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.2\libnvvp;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\Program Files\MATLAB\R2019b\runtime\win64;C:\Program Files\MATLAB\R2019b\bin;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Microsoft SQL Server\Client SDK\ODBC\110\Tools\Binn;C:\Program Files (x86)\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\Tools\Binn;C:\Program Files\Microsoft SQL Server\120\DTS\Binn;C:\Program Files (x86)\Windows Kits\8.1\Windows Performance Toolkit;C:\Program Files\Microsoft SQL Server\110\Tools\Binn;C:\Program Files\NVIDIA Corporation\Nsight Compute 2019.5.0;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Program Files\nodejs;C:\ProgramData\chocolatey\bin;C:\Program Files\PowerShell\7;D:\git-annex-remote-rclone;C:\Users\mvdmlab\AppData\Local\Microsoft\WindowsApps;C:\ProgramData\mvdmlab\GitHubDesktop\bin;C:\Users\mvdmlab\AppData\Roaming\npm;C:\Users\mvdmlab\AppData\Local\GitHubDesktop\bin;C:\Users\mvdmlab\miniconda3\Library\git-annex-remote-rclone;.
## extensions
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - TorrentParser
    - Feeds
    - Testsuite
  - dependency versions:
    - aws-0.21.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.4
    - feed-1.2.0.1
    - ghc-8.6.5
    - http-client-0.6.4
    - persistent-sqlite-2.9.3
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0.1
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
  - operating system: mingw32 x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions:
    - 8
  - upgrade supported from repository versions:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20200331-gb11931a4a
## location
  - path: D:\data-formats
  - type: dataset
## metadata_extractors
  - annex:
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio:
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - datacite:
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core:
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822:
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif:
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage:
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image:
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp:
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## python
  - implementation: CPython
  - version: 3.7.7
## system
  - distribution:   10/10.0.18362/SP0
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: cp1252
  - max_path_length: 276
  - name: Windows
  - release: 10
  - type: nt
  - version: 10.0.18362

**Comment by mih** [comment]
Possibly related to #3725

**Comment by adswa** [comment]
I tried to reproduce this on my Windows development machine with the same dataset using CMD and Powershell (which seemed to have been used in the first comment). 

I failed to reproduce the bug, files were downloaded successfully with both terminals.

<details><summary>WTF</summary>

```
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials
  - keyring:
    - active_backends:
      - Windows WinVaultKeyring
      - Windows RegistryKeyring
      - EncryptedKeyring with not defined v.1.0 at C:\Users\adina\AppData\Local\Python Keyring\wincrypto_pass.cfg
      - PlaintextKeyring with no encyption v.1.0 at C:\Users\adina\AppData\Local\Python Keyring\keyring_pass.cfg
    - config_file: C:\Users\adina\AppData\Local\Python Keyring\keyringrc.cfg
    - data_root: C:\Users\adina\AppData\Local\Python Keyring
## datalad
  - version: 0.17.9+160.g38fd0e8e8
## dataset
  - branches:
    - adjusted/master(unlocked)@3fff084
    - git-annex@35aba0f
    - master@f9cdf38
  - id: f4bba2f8-a9d2-11ea-a6f2-002590f97d84
  - path: C:\Users\adina\testing\BiconditionalOdor
  - repo: AnnexRepo
## dependencies
  - annexremote: 1.6.0
  - boto: 2.49.0
  - cmd:7z: 21.05
  - cmd:annex: 10.20220928-g82dab0749
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.37.3.windows.1
  - cmd:ssh: 8.1p1
  - cmd:system-git: 2.37.3.windows.1
  - cmd:system-ssh: 8.1p1
  - humanize: 4.4.0
  - iso8601: 1.0.2
  - keyring: 23.9.3
  - keyrings.alt: 4.2.0
  - msgpack: 1.0.4
  - platformdirs: 2.5.2
  - requests: 2.28.1
## environment
  - PATH: C:\Users\adina\env\gooyey\Scripts;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Git\cmd;C:\Users\adina\AppData\Local\Programs\Python\Python310\Scripts\;C:\Users\adina\AppData\Local\Programs\Python\Python310\;C:\Users\adina\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\adina\AppData\Local\Programs\Python\Python39\;C:\Users\adina\AppData\Local\Microsoft\WindowsApps;C:\Users\adina\AppData\Local\Programs\Microsoft VS Code\bin;C:\Program Files\ptime;C:\Program Files\7-Zip;C:\Program Files (x86)\Vim\vim82;C:\Program Files\Inkscape\bin
## extensions
  - gooey:
    - description: Gooey (GUI)
    - entrypoints:
      - datalad_gooey.askpass.GooeyAskPass:
        - class: GooeyAskPass
        - load_error: None
        - module: datalad_gooey.askpass
        - names:
          - gooey-askpass
          - gooey_askpass
      - datalad_gooey.gooey.Gooey:
        - class: Gooey
        - load_error: None
        - module: datalad_gooey.gooey
        - names:
      - datalad_gooey.lsdir.GooeyLsDir:
        - class: GooeyLsDir
        - load_error: None
        - module: datalad_gooey.lsdir
        - names:
          - gooey-lsdir
          - gooey_lsdir
      - datalad_gooey.status_light.GooeyStatusLight:
        - class: GooeyStatusLight
        - load_error: None
        - module: datalad_gooey.status_light
        - names:
          - gooey-status-light
          - gooey_status_light
    - load_error: None
    - module: datalad_gooey
    - version: 0.1.0+188.g26cba1f
  - next:
    - description: What is next in DataLad
    - entrypoints:
      - datalad_next.create_sibling_webdav.CreateSiblingWebDAV:
        - class: CreateSiblingWebDAV
        - load_error: None
        - module: datalad_next.create_sibling_webdav
        - names:
          - create-sibling-webdav
      - datalad_next.credentials.Credentials:
        - class: Credentials
        - load_error: None
        - module: datalad_next.credentials
        - names:
      - datalad_next.tree.TreeCommand:
        - class: TreeCommand
        - load_error: None
        - module: datalad_next.tree
        - names:
          - tree
    - load_error: None
    - module: datalad_next
    - version: 0.6.3+43.g4f528d3
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - TorrentParser
    - MagicMime
    - Benchmark
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions:
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.29
    - DAV-1.3.4
    - feed-1.3.2.0
    - ghc-8.10.7
    - http-client-0.7.9
    - persistent-sqlite-2.13.0.3
    - torrent-10000.1.1
    - uuid-1.3.15
    - yesod-1.6.1.2
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 10
  - operating system: mingw32 x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions:
    - 8
    - 9
    - 10
  - upgrade supported from repository versions:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20220928-g82dab0749
## location
  - path: C:\Users\adina\testing\BiconditionalOdor
  - type: dataset
## python
  - implementation: CPython
  - version: 3.10.7
## system
  - distribution:   10/10.0.19044/SP0/Multiprocessor Free
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: cp1252
  - filesystem:
    - CWD:
      - max_pathlength: 260
      - mount_opts: rw,fixed
      - path: C:\Users\adina\testing\BiconditionalOdor\M040-2020-04-28-CDOD11
      - type: NTFS
    - HOME:
      - max_pathlength: 260
      - mount_opts: rw,fixed
      - path: C:\Users\adina
      - type: NTFS
    - TMP:
      - max_pathlength: 260
      - mount_opts: rw,fixed
      - path: C:\Users\adina\AppData\Local\Temp
      - type: NTFS
  - max_path_length: 319
  - name: Windows
  - release: 10
  - type: nt
  - version: 10.0.19044
```

</details>
