### ISSUE TITLE
error with datalad install

### ISSUE THREAD

**Issue by alienx-zero** [datalad/datalad#4892]
It is the first time for me to use datalad to download data~ And here is the error info in cmd. 
E:\OPT\research\fMRI\test>datalad install https://github.com/OpenNeuroDatasets/ds002372.git
[ERROR] [WinError 2] The system cannot find the file specified [subprocess.py:_execute_child:1178] (FileNotFoundError)

**Comment by mih** [comment]
Hey, and thx for the report. Can you run this again with `datalad -l debug install ...` so we can see a bit more on what is happening. Please also post the output of `datalad wtf`.

**Comment by alienx-zero** [comment]
Here is the output of debug:
![1是、599417514(1)](https://user-images.githubusercontent.com/55502834/92332903-e4810f00-f04e-11ea-803c-1d603a916d64.png)

**Comment by alienx-zero** [comment]
Here is wtf:
E:\OPT\research\fMRI\test>datalad wtf
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## datalad
  - full_version: 0.13.3
  - version: 0.13.3
## dependencies
  - annexremote: 1.4.3
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:annex: 8.20200720.2-g8bfa7990b
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.25.1.windows.1
  - cmd:system-git: 2.25.1.windows.1
  - cmd:system-ssh: for
  - humanize: 2.6.0
  - iso8601: 0.1.12
  - keyring: 21.1.0
  - keyrings.alt: 3.4.0
  - msgpack: 0.6.1
  - requests: 2.22.0
  - scrapy: 2.3.0
  - wrapt: 1.11.2
## environment
  - PATH: C:\Python38\Scripts\;C:\Python38\;D:\Program Files (x86)\NetSarang\Xshell 6\;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\bin;C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v9.0\libnvvp;D:\Program Files (x86)\Java\jdk-13.0.1;D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\bin;D:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0\libnvvp;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;d:\Program Files\MATLAB\R2019b\bin;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\Program Files (x86)\Java\jdk-13.0.1\bin;D:\Program Files (x86)\Java\jdk-13.0.1\jre\bin;D:\Users\99488\Anaconda3\condabin;D:\Users\99488\Anaconda3;D:\Users\99488\Anaconda3\Scripts;D:\Program Files\NVIDIA Corporation\NVSMI;d:\Program Files\Git\cmd;D:\Program Files\cmake-3.16.8-win64-x64\bin;D:\Program Files\swigwin-4.0.1;C:\ProgramData\chocolatey\bin;C:\msys64\usr\bin;C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\MSBuild\Current\Bin\amd64;;C:\Program Files\Docker\Docker\resources\bin;C:\ProgramData\DockerDesktop\version-bin;E:\Program Files\nodejs\;E:\Program Files\Amazon\AWSCLI\;C:\Users\99488\AppData\Local\Microsoft\WindowsApps;D:\Users\99488\Anaconda3;D:\Users\99488\Anaconda3\Scripts;D:\Users\99488\Anaconda3\Library\bin;D:\Users\99488\Anaconda3\condabin;D:\Program Files\NVIDIA Corporation\NVSMI;D:\Program Files\JetBrains\PyCharm Community Edition 2019.3.3\bin;;D:\Program Files\texlive\2020\bin\win32;C:\msys64;C:\Users\99488\AppData\Roaming\npm
## extensions
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - TorrentParser
    - Feeds
    - Testsuite
  - dependency versions:
    - aws-0.21.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.4
    - feed-1.2.0.1
    - ghc-8.6.5
    - http-client-0.5.14
    - persistent-sqlite-2.9.3
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0.1
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: mingw32 x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions:
    - 8
  - upgrade supported from repository versions:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20200720.2-g8bfa7990b
## location
  - path: E:\OPT\research\fMRI\test
  - type: directory
## metadata_extractors
  - annex:
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio:
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - datacite:
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core:
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822:
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif:
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage:
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image:
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp:
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## python
  - implementation: CPython
  - version: 3.7.4
## system
  - distribution:   10/10.0.18362/SP0
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: cp65001
  - max_path_length: 259
  - name: Windows
  - release: 10
  - type: nt
  - version: 10.0.18362

**Comment by riedelmax** [comment]
Hello everyone? Is there a fix for this issue yet?

**Comment by riedelmax** [comment]
Hello everyone,

I have a pretty ugly workaround for this issue.

Im on Windows 10 and my git-annex installation placed a file `git-annex.cmd` in `C:\Program Files\Git\cmd\`. When I call `subprocess.Popen('git-annex')` I get the FileNotFoundError. It works however, when i call `subprocess.Popen('git-annex.cmd')`. So I places the following 2 lines in `datalad/cmd.py` after line 205:

`if cmd[0] == 'git-annex':
    cmd[0] = 'git-annex.cmd'`

I don't know if it is save or if it breaks other things, but for the moment this works and I was able to create a dataset.

**Comment by adswa** [comment]
Sorry for the silence on this, we're still only setting up dedicated hardware for investigating and dealing with Windows issues. But: I got a fresh Windows 10 computer today, and will try to find out what's wrong.

In a fresh, bleeding edge set-up, I am not able to replicate the error, the installation proceeds fine, for all datasets shown in this issue and with DataLad versions starting at 0.13.3. I'll include a ```datalad wtf``` at the end of this issue. 

> Im on Windows 10 and my git-annex installation placed a file git-annex.cmd in C:\Program Files\Git\cmd\. When I call subprocess.Popen('git-annex') I get the FileNotFoundError. It works however, when i call subprocess.Popen('git-annex.cmd'). So I places the following 2 lines in datalad/cmd.py after line 205:

This may be a place to start looking for a place to look for a cause. How and where did you install Git and git-annex on your system? I used the installation instructions from the handbook, and both Git and git-annex are installed within ``C:\Users\<user>\miniconda3\Library``, and I execute datalad commands within the Anaconda Prompt -  is that true for you, too?

<details><summary> Here's how my system is set up</summary>

```
(base) C:\Users\datalad\testing\with013>datalad wtf
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## datalad
  - full_version: 0.13.4
  - version: 0.13.4
## dependencies
  - annexremote: 1.4.3
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:annex: 8.20200815-g335aae266
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.28.0.windows.1
  - cmd:system-git: 2.28.0.windows.1
  - cmd:system-ssh: 8.3p1
  - humanize: 3.0.1
  - iso8601: 0.1.13
  - keyring: 21.4.0
  - keyrings.alt: 4.0.0
  - msgpack: 1.0.0
  - requests: 2.23.0
  - wrapt: 1.12.1
## environment
  - PATH: C:\Users\datalad\miniconda3;C:\Users\datalad\miniconda3\Library\mingw-w64\bin;C:\Users\datalad\miniconda3\Library\usr\bin;C:\Users\datalad\miniconda3\Library\bin;C:\Users\datalad\miniconda3\Scripts;C:\Users\datalad\miniconda3\bin;C:\Users\datalad\miniconda3\condabin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Users\datalad\AppData\Local\Microsoft\WindowsApps;.
## extensions
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - S3
    - WebDAV
    - TorrentParser
    - Feeds
    - Testsuite
  - dependency versions:
    - aws-0.21.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.25
    - DAV-1.3.4
    - feed-1.2.0.1
    - ghc-8.6.5
    - http-client-0.5.14
    - persistent-sqlite-2.9.3
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.0.1
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: mingw32 x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - hook
    - external
  - supported repository versions:
    - 8
  - upgrade supported from repository versions:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20200815-g335aae266
## location
  - path: C:\Users\datalad\testing\with013
  - type: directory
## metadata_extractors
  - annex:
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio:
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - datacite:
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core:
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822:
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif:
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage:
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image:
    - load_error: No module named 'PIL' [image.py:<module>:16]
    - module: datalad.metadata.extractors.image
  - xmp:
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## python
  - implementation: CPython
  - version: 3.8.3
## system
  - distribution: msys_nt-10.0-19041/3.1.6  10/10.0.19041/SP0/Multiprocessor Free
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: cp1252
  - max_path_length: 259
  - name: Windows
  - release: 10
  - type: nt
  - version: 10.0.19041
```

</details>
