### ISSUE TITLE
TRAVIS: make cron jobs not even start the VM

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5189]
ATM we have
```yaml
before_install:
  - if [ ! -z "${_DL_CRON:-}" ]; then
      if [ ! ${TRAVIS_EVENT_TYPE} = "cron" ]; then
        echo "Exiting since should only be ran on a weekly basis by cron!";
        exit 0;
      fi
    fi
```
so it requires first for a machine to boot, waste of time.
Not yet sure exactly how but https://github.com/travis-ci/travis-ci/issues/7149#issuecomment-335825605 

```yaml
language: python
python:
  - "3.6"
matrix:
  include:
    - if: branch =~ ^deploy
      python: "2.7"
```
suggests that we could add conditional to those to not even be considered if some expression is not matched.

There is also "stages" feature https://blog.travis-ci.com/2017-09-12-build-stages-order-and-conditions so may be we could have some stages (tests and extra-tests) or alike, again where some are triggered only for cron jobs.  @jwodder please have a look either you see a clean way
