### ISSUE TITLE
tributors: should not submit PRs to forks

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#5193]
incident: https://github.com/jwodder/datalad/pull/1

result of the merge of #4789 , might need workflow tune up, @vsoch - do you have a moment to tune it up to the "best con/tributors practices"?

**Comment by vsoch** [comment]
@yarikoptic I think that's in the settings for the repository?

**Comment by yarikoptic** [comment]
indeed, now that all forks have a copy of that workflow it would run for them as well, and they could selectively disable it in Settings -> Actions I guess, but IMHO it is simply not a desirable default behavior: most likely we should just limit that workflow to run only when ran on master of this (not any fork) repository.

**Comment by vsoch** [comment]
You could then have it stop before it does anything by defining it in the workflow, e.g.,

```yaml
if: contains(github.repository, "datalad/datalad")
steps:
 - run: echo "I only run if datalad/datalab is running the action"
```
Not tested, but some derivative of the above should work :)
