### ISSUE TITLE
Datalad python logger initialises in 'info' if logging.basicConfig is called

### ISSUE THREAD

**Issue by fraimondo** [datalad/datalad#5652]
#### What is the problem?
If using the Python API, when calling `logging.basicConfig`, datalad automatically starts logging all info messages, without accounting for the root logger level.

#### What steps will reproduce the problem?

```Python
import sys
import logging
import datalad.api

# Comment / uncomment this line to hide/see datalad info messages
logging.basicConfig(stream=sys.stdout, level=logging.WARN)

logger = logging.getLogger("TEST")
logger.setLevel(logging.WARN)

REPO_URL = ('git@github.com:datalad-datasets/'
            'human-connectome-project-openaccess.git')

db_path = './hcp'  # to run the example, make sure it does not exist
logger.info('This should not appear')
logger.warning('This should appear')

datalad.api.install(source=REPO_URL, path=db_path)
```

#### What version of DataLad are you using (run `datalad --version`)? On what operating system (consider running `datalad wtf`)?
```
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials 
  - keyring: 
    - active_backends: 
      - macOS Keyring
      - PlaintextKeyring with no encyption v.1.0 at /Users/fraimondo/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /Users/fraimondo/.config/python_keyring/keyringrc.cfg
    - data_root: /Users/fraimondo/.local/share/python_keyring
## datalad 
  - full_version: 0.14.4
  - version: 0.14.4
## dataset 
  - id: None
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /Users/fraimondo/dev/projects/Event_Detection
  - repo: GitRepo
## dependencies 
  - annexremote: 1.2.1
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:annex: 8.20210127
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.24.3
  - cmd:system-git: 2.24.3
  - cmd:system-ssh: 8.1p1
  - humanize: 3.5.0
  - iso8601: 0.1.14
  - keyring: 22.3.0
  - keyrings.alt: 4.0.2
  - msgpack: 1.0.2
  - requests: 2.25.1
  - wrapt: 1.12.1
## environment 
  - LC_CTYPE: UTF-8
  - PATH: /Users/fraimondo/Applications/workbench/bin_macosx64:/Users/fraimondo/.rbenv/shims:/Users/fraimondo/dev/tbox/freesurfer/bin:/Users/fraimondo/dev/tbox/freesurfer/fsfast/bin:/Users/fraimondo/dev/tbox/fsl/bin:/Users/fraimondo/dev/tbox/freesurfer/mni/bin:/usr/local/opt/ruby/bin:/Users/fraimondo/anaconda3/envs/event_detect/bin:/Users/fraimondo/anaconda3/condabin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/fraimondo/.platformio/penv/bin:/Users/fraimondo/gems/bin:/Users/fraimondo/.gem/ruby/3.0.0/bin
## extensions 
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - FsEvents
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.28
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.10.3
    - http-client-0.7.4
    - persistent-sqlite-2.11.0.0
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.1.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: darwin x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20210127
## location 
  - path: /Users/fraimondo/dev/projects/Event_Detection
  - type: dataset
## metadata_extractors 
  - annex (datalad 0.14.4): 
    - distribution: datalad 0.14.4
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.14.4): 
    - distribution: datalad 0.14.4
    - load_error: No module named 'mutagen' [audio.py:<module>:17]
    - module: datalad.metadata.extractors.audio
  - datacite (datalad 0.14.4): 
    - distribution: datalad 0.14.4
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.14.4): 
    - distribution: datalad 0.14.4
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.14.4): 
    - distribution: datalad 0.14.4
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.14.4): 
    - distribution: datalad 0.14.4
    - load_error: No module named 'exifread' [exif.py:<module>:16]
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage (datalad 0.14.4): 
    - distribution: datalad 0.14.4
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.14.4): 
    - distribution: datalad 0.14.4
    - load_error: No module named 'PIL' [image.py:<module>:16]
    - module: datalad.metadata.extractors.image
  - xmp (datalad 0.14.4): 
    - distribution: datalad 0.14.4
    - load_error: No module named 'libxmp' [xmp.py:<module>:20]
    - module: datalad.metadata.extractors.xmp
## metadata_indexers 
## python 
  - implementation: CPython
  - version: 3.9.4
## system 
  - distribution: darwin/20.4.0 10.16/x86_64
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 322
  - name: Darwin
  - release: 20.4.0
  - type: posix
  - version: Darwin Kernel Version 20.4.0: Thu Apr 22 21:46:47 PDT 2021; root:xnu-7195.101.2~1/RELEASE_X86_64
```
#### Is there anything else that would be useful to know in this context?

It's get solved by setting the logging level back to WARN:

```
import sys
import logging
import datalad.api
from datalad.log import lgr as _dllgr

# Comment / uncomment this line to hide/see datalad info messages
logging.basicConfig(stream=sys.stdout, level=logging.WARN)

logger = logging.getLogger("TEST")
logger.setLevel(logging.WARN)
_dllgr.setLevel(logging.WARN)
```

#### Have you had any success using DataLad before? (to assess your expertise/prior luck.  We would welcome your testimonial additions to https://github.com/datalad/datalad/wiki/Testimonials as well)

Despite this little bug (that is filling my logs with clone/get progress), everything is being smooth. It will be tough to not use datalad.
