### ISSUE TITLE
Request: datalad run pick up environment variables from committed file

### ISSUE THREAD

**Issue by effigies** [datalad/datalad#6119]
### What is the problem?

Consider a case where I want to manage development in a virtual environment:

```Shell
datalad create -c yoda analysis
cd analysis
mkdir sourcedata
datalad install -d . -s ///input/dataset sourcedata/rawdata
datalad install -d . -s https://github.com/org/project.git code/project
(
  cd code
  pipenv install -e ./project/
)
datalad save
```

If I want to `datalad run` in the pipenv, I can't do it directly from the dataset root:

```Shell
$ datalad run pipenv --venv
[INFO   ] == Command start (output follows) ===== 
No virtualenv has been created for this project(/path/to/analysis) yet!
Aborted!
[INFO   ] == Command exit (modification check follows) ===== 
[INFO   ] The command had a non-zero exit code. If this is expected, you can save the changes with 'datalad save -d . -r -F .git/COMMIT_EDITMSG' 
CommandError: 'pipenv --venv' failed with exitcode 1 under /path/to/analysis
```

I need to do something like:

```Shell
PIPENV_PIPFILE=code/Pipfile datalad run pipenv --venv
```

While I can make this the default behavior by setting my environment variable, it would be more reproducible if I could store the relevant environment variables in the repository itself:

```Shell
cat PIPENV_PIPFILE=code/Pipfile > .env
datalad save -m "Use virtual environments defined in code/"
datalad run pipenv run mycommand
```

### What steps will reproduce the problem?

Not a problem.

### Datalad information

<details>
<summary>Click</summary>

```YAML
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials 
  - keyring: 
    - active_backends: 
      - SecretService Keyring
      - PlaintextKeyring with no encyption v.1.0 at /home/chris/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/chris/.config/python_keyring/keyringrc.cfg
    - data_root: /home/chris/.local/share/python_keyring
## datalad 
  - full_version: 0.15.0+38.ga50434e0c
  - version: 0.15.0+38.ga50434e0c
## dataset 
  - branches: 
    - git-annex@fbe9fc5
    - main@9e97a0c
  - id: 8dbafd81-b50e-431a-b1e8-df08ca523557
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /data/out/ds001734-fitlins
  - repo: AnnexRepo
## dependencies 
  - annexremote: 1.5.0
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:annex: 8.20210903-1~ndall+1
  - cmd:bundled-git: 2.30.2
  - cmd:git: 2.30.2
  - cmd:system-git: 2.25.1
  - cmd:system-ssh: 8.2p1
  - humanize: 3.11.0
  - iso8601: 0.1.16
  - keyring: 23.2.1
  - keyrings.alt: 4.1.0
  - msgpack: 1.0.2
  - requests: 2.26.0
  - wrapt: 1.12.1
## environment 
  - LANG: en_US.UTF-8
  - PATH: /home/chris/bin:/usr/local/lib/nodejs/node-v14.16.1-linux-x64/bin:/usr/local/freesurfer/7.2.0/bin:/usr/local/freesurfer/7.2.0/fsfast/bin:/usr/local/freesurfer/7.2.0/tktools:/usr/share/fsl/5.0/bin:/usr/local/freesurfer/7.2.0/mni/bin:/home/chris/abin:/home/chris/bin:/home/chris/bin:/home/chris/.cargo/bin:/home/chris/miniconda3/envs/datalad16/bin:/home/chris/miniconda3/condabin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/usr/lib/fsl/5.0
## extensions 
  - osf: 
    - description: DataLad extension for OSF support
    - entrypoints: 
      - datalad_osf.create_sibling_osf.CreateSiblingOSF: 
        - class: CreateSiblingOSF
        - load_error: None
        - module: datalad_osf.create_sibling_osf
        - names: 
          - create-sibling-osf
          - create_sibling_osf
      - datalad_osf.credentials.OSFCredentials: 
        - class: OSFCredentials
        - load_error: None
        - module: datalad_osf.credentials
        - names: 
          - osf-credentials
          - osf_credentials
    - load_error: None
    - module: datalad_osf
    - version: 0.2.3.1
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.26
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.8.4
    - http-client-0.6.4.1
    - persistent-sqlite-2.10.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.1.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 8
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20210903-1~ndall+1
## location 
  - path: /data/out/ds001734-fitlins
  - type: dataset
## metadata_extractors 
  - annex (datalad 0.15.0+38.ga50434e0c): 
    - distribution: datalad 0.15.0+38.ga50434e0c
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.15.0+38.ga50434e0c): 
    - distribution: datalad 0.15.0+38.ga50434e0c
    - load_error: ModuleNotFoundError(No module named 'mutagen')
    - module: datalad.metadata.extractors.audio
  - datacite (datalad 0.15.0+38.ga50434e0c): 
    - distribution: datalad 0.15.0+38.ga50434e0c
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.15.0+38.ga50434e0c): 
    - distribution: datalad 0.15.0+38.ga50434e0c
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.15.0+38.ga50434e0c): 
    - distribution: datalad 0.15.0+38.ga50434e0c
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.15.0+38.ga50434e0c): 
    - distribution: datalad 0.15.0+38.ga50434e0c
    - load_error: ModuleNotFoundError(No module named 'exifread')
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage (datalad 0.15.0+38.ga50434e0c): 
    - distribution: datalad 0.15.0+38.ga50434e0c
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.15.0+38.ga50434e0c): 
    - distribution: datalad 0.15.0+38.ga50434e0c
    - load_error: ModuleNotFoundError(No module named 'PIL')
    - module: datalad.metadata.extractors.image
  - xmp (datalad 0.15.0+38.ga50434e0c): 
    - distribution: datalad 0.15.0+38.ga50434e0c
    - load_error: ModuleNotFoundError(No module named 'libxmp')
    - module: datalad.metadata.extractors.xmp
## metadata_indexers 
## python 
  - implementation: CPython
  - version: 3.9.7
## system 
  - distribution: ubuntu/20.04/focal
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 282
  - name: Linux
  - release: 5.11.0-38-generic
  - type: posix
  - version: #42~20.04.1-Ubuntu SMP Tue Sep 28 20:41:07 UTC 2021
```

</details>

### Have you had any success using DataLad before?

Yes.
