### ISSUE TITLE
`datalad clone` does not actually stop when target path not empty

### ISSUE THREAD

**Issue by AKSoo** [datalad/datalad#6138]
### What is the problem?

`datalad clone` should do nothing if target is not empty, but it currently proceeds with some steps and corrupts the dataset. Any modified file in the target path gets saved, and you get `[WARNING] Failed to get 'code.path', skipping this submodule` whenever you do anything with subdatasets.

### What steps will reproduce the problem?

1. Have a non-empty directory `dir` in dataset
2. `datalad clone -d^ $URL dir` (very plausible user error)

### Datalad information

datalad 0.15.2

```
## system 
  - distribution: arch
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 270
  - name: Linux
  - release: 5.10.75-1-lts
  - type: posix
  - version: #1 SMP Wed, 20 Oct 2021 11:02:09 +0000
```

### Additional context

Example log
```
install(error): code (dataset) [target path already exists and not empty, refuse to clone into target path]
add(ok): code/ba.sh (file)                                                                                                                                                                                                                    
save(ok): . (dataset)                                                                                                                                                                                                                         
[WARNING] Failed to get 'code.path', skipping this submodule                                                                                                                                                                                  
[WARNING] Failed to get 'code.path', skipping this submodule 
add(ok): .gitmodules (file)                                                                                                                                                                                                                   
save(ok): . (dataset)
action summary:
  add (ok: 2)
  install (error: 1)
  save (ok: 2)
```
