### ISSUE TITLE
Outcome of saving staged files

### ISSUE THREAD

**Issue by Remi-Gau** [datalad/datalad#6400]
### What is the problem?

The outcome of saving a staged file feels a bit hard to guess from a user perspective.

I would have expected a file staged with `git add` to end up being annexed if the datalad config used says it should be.

Current behavior seems to be that it won't be annexed with the default config, but will be if using the `text2git` config.

Tagging @mwmaclean who pointed this out to me.

## default config

```bash
datalad create test

cd test

cp ~/Pictures/coding_with_bob_ross.png .
git add coding_with_bob_ross.png
datalad save -m 'save staged image 1'

cp ~/Pictures/index.jpeg .
datalad save -m 'save image 2'

git annex find .
```

Returns:
- `index.jpeg`

## text2git config

```bash
datalad create -c text2git test
cd test

cp ~/Pictures/coding_with_bob_ross.png .
git add coding_with_bob_ross.png
datalad save -m 'save staged image 1'

cp ~/Pictures/index.jpeg .
datalad save -m 'save image 2'

git annex find .
```

Returns

- `coding_with_bob_ross.png`
- `index.jpeg`

### Datalad information

Not sure if if is needed but here is my WTF

 ```
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials 
  - keyring: 
    - active_backends: 
      - SecretService Keyring
      - PlaintextKeyring with no encyption v.1.0 at /home/remi/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/remi/.config/python_keyring/keyringrc.cfg
    - data_root: /home/remi/.local/share/python_keyring
## datalad 
  - version: 0.15.4
## dataset 
  - branches: 
    - git-annex@5500cf0
    - master@1881621
  - id: 5877a93f-561c-4db2-9379-045db4466b58
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: /home/remi/test/test
  - repo: AnnexRepo
## dependencies 
  - annexremote: 1.5.0
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 8.20211123+git12-g02e3756bd-1~ndall+1
  - cmd:bundled-git: 2.30.2
  - cmd:git: 2.30.2
  - cmd:system-git: 2.24.0
  - cmd:system-ssh: 7.6p1
  - humanize: 3.14.0
  - iso8601: 1.0.2
  - keyring: 23.5.0
  - keyrings.alt: 4.1.0
  - msgpack: 1.0.3
  - requests: 2.25.1
  - wrapt: 1.13.3
## environment 
  - GIT_ASKPASS: /usr/share/code/resources/app/extensions/git/dist/askpass.sh
  - LANG: en_US.UTF-8
  - LANGUAGE: en_US
  - LC_ADDRESS: en_GB.UTF-8
  - LC_IDENTIFICATION: en_GB.UTF-8
  - LC_MEASUREMENT: en_GB.UTF-8
  - LC_MONETARY: en_GB.UTF-8
  - LC_NAME: en_GB.UTF-8
  - LC_NUMERIC: en_GB.UTF-8
  - LC_PAPER: en_GB.UTF-8
  - LC_TELEPHONE: en_GB.UTF-8
  - LC_TIME: en_GB.UTF-8
  - PATH: /home/remi/miniconda3/bin:/home/remi/miniconda3/condabin:/home/remi/.nvm/versions/node/v14.16.0/bin:/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin:/usr/local/fsl/bin:/home/remi/.local/bin:/home/remi/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/remi/github/miss_hit:/home/remi/abin:/home/remi/github/miss_hit:/home/remi/abin
## extensions 
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.26
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.8.4
    - http-client-0.6.4.1
    - persistent-sqlite-2.10.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.1.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 8
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20211123+git12-g02e3756bd-1~ndall+1
## location 
  - path: /home/remi/test/test
  - type: dataset
## metadata_extractors 
  - annex (datalad 0.15.4): 
    - distribution: datalad 0.15.4
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.15.4): 
    - distribution: datalad 0.15.4
    - load_error: ModuleNotFoundError(No module named 'mutagen')
    - module: datalad.metadata.extractors.audio
  - datacite (datalad 0.15.4): 
    - distribution: datalad 0.15.4
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.15.4): 
    - distribution: datalad 0.15.4
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.15.4): 
    - distribution: datalad 0.15.4
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.15.4): 
    - distribution: datalad 0.15.4
    - load_error: ModuleNotFoundError(No module named 'exifread')
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage (datalad 0.15.4): 
    - distribution: datalad 0.15.4
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.15.4): 
    - distribution: datalad 0.15.4
    - load_error: ModuleNotFoundError(No module named 'PIL')
    - module: datalad.metadata.extractors.image
  - xmp (datalad 0.15.4): 
    - distribution: datalad 0.15.4
    - load_error: ModuleNotFoundError(No module named 'libxmp')
    - module: datalad.metadata.extractors.xmp
## metadata_indexers 
## python 
  - implementation: CPython
  - version: 3.9.5
## system 
  - distribution: ubuntu/18.04/bionic
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 276
  - name: Linux
  - release: 5.4.0-96-generic
  - type: posix
  - version: #109~18.04.1-Ubuntu SMP Thu Jan 13 15:06:26 UTC 2022
 ```

### Have you had any success using DataLad before?

Yes though it does not seem I am using the `--help` flag any less frequently.
