### ISSUE TITLE
Feature request: Progress bar for `datalad unlock .`

### ISSUE THREAD

**Issue by sappelhoff** [datalad/datalad#6691]
### What is the problem?

I sometimes want to unlock an entire dataset via `datalad unlock .` (for example when all files will be overwritten, or when I am too lazy to define a proper `datalad run` command that takes care of unlocking).

For big datasets, this unlock operation can take a long time (up to several minutes) -- it would be nice if we could have a progress bar throughout the operation.

### What steps will reproduce the problem?

- `datalad clone https://gin.g-node.org/sappelhoff/eeg_manypipes_arc/`
- `cd eeg_manypipes_arc`
- `datalad unlock .`

### Datalad information

Click "details"

<details>

```
/home/stefanappelhoff/miniconda3/envs/emp/lib/python3.10/site-packages/secretstorage/util.py:46: UserWarning: Passing unwrap= to .send_and_get_reply() is deprecated and will break in a future version of Jeepney.
  return self._connection.send_and_get_reply(msg, unwrap=True)
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials 
  - keyring: 
    - active_backends: 
      - SecretService Keyring
      - PlaintextKeyring with no encyption v.1.0 at /home/stefanappelhoff/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/stefanappelhoff/.config/python_keyring/keyringrc.cfg
    - data_root: /home/stefanappelhoff/.local/share/python_keyring
## datalad 
  - version: 0.15.6
## dependencies 
  - annexremote: 1.6.0
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 10.20220322-g7b64dea
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.35.1
  - cmd:system-git: 2.35.1
  - cmd:system-ssh: 9.0p1
  - humanize: 4.0.0
  - iso8601: 1.0.2
  - keyring: 23.5.0
  - keyrings.alt: 4.1.0
  - msgpack: 1.0.3
  - requests: 2.27.1
  - wrapt: 1.14.0
## environment 
  - LANG: en_US.UTF-8
  - LC_ADDRESS: de_DE.UTF-8
  - LC_IDENTIFICATION: de_DE.UTF-8
  - LC_MEASUREMENT: de_DE.UTF-8
  - LC_MONETARY: de_DE.UTF-8
  - LC_NAME: de_DE.UTF-8
  - LC_NUMERIC: de_DE.UTF-8
  - LC_PAPER: de_DE.UTF-8
  - LC_TELEPHONE: de_DE.UTF-8
  - LC_TIME: de_DE.UTF-8
  - PATH: /home/stefanappelhoff/miniconda3/envs/emp/bin:/home/stefanappelhoff/miniconda3/condabin:/home/stefanappelhoff/.local/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/stefanappelhoff/miniconda3/bin:/home/stefanappelhoff/Desktop/bids/bids-validator/bids-validator/bin:/home/stefanappelhoff/Desktop/bids/open-trigger-box/figure1_generation:/home/stefanappelhoff/diff-so-fancy
## extensions 
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.29
    - DAV-1.3.4
    - feed-1.3.2.0
    - ghc-8.10.7
    - http-client-0.7.9
    - persistent-sqlite-2.13.0.3
    - torrent-10000.1.1
    - uuid-1.3.15
    - yesod-1.6.1.2
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
    - 9
    - 10
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20220322-g7b64dea
## location 
  - path: /home/stefanappelhoff
  - type: directory
## metadata_extractors 
  - annex (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.annex
    - version: None
  - audio (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: ModuleNotFoundError(No module named 'mutagen')
    - module: datalad.metadata.extractors.audio
  - datacite (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.datacite
    - version: None
  - datalad_core (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
    - version: None
  - datalad_rfc822 (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
    - version: None
  - exif (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: ModuleNotFoundError(No module named 'exifread')
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
    - version: None
  - image (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: None
    - module: datalad.metadata.extractors.image
    - version: None
  - xmp (datalad 0.15.6): 
    - distribution: datalad 0.15.6
    - load_error: ModuleNotFoundError(No module named 'libxmp')
    - module: datalad.metadata.extractors.xmp
## metadata_indexers 
## python 
  - implementation: CPython
  - version: 3.10.4
## system 
  - distribution: ubuntu/18.04/Bionic Beaver
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 277
  - name: Linux
  - release: 5.4.0-110-generic
  - type: posix
  - version: #124~18.04.1-Ubuntu SMP Fri Apr 22 12:01:21 UTC 2022

```
</details>
