### ISSUE TITLE
`datalad save $path` does not automatically register new subdatasets

### ISSUE THREAD

**Issue by jwodder** [datalad/datalad#6775]
### What is the problem?

If a subdataset is cloned into a superdataset with `datalad clone` without using the `-d` option to register & commit the subdataset automatically, then trying to register & save the subdataset with `datalad save $path` will do nothing.  This is in contrast to `datalad save` without any paths, which automatically detects & registers the new subdataset.

### What steps will reproduce the problem?

Setup:

```
datalad create foo
cd foo
echo 'This is a file.' > file.txt
datalad save -m 'Add a file'
cd ..
```

If you clone and then save without specifying a path, the save fills in .gitmodules:

```
datalad create super
datalad clone foo super/foo
cd super
datalad save -m 'Add a subdataset'
# foo is now a submodule
```

but if you do "datalad save foo" instead:

```
datalad create super
datalad clone foo super/foo
cd super
datalad save -m 'Add a subdataset' foo
```

then nothing is saved!

### Datalad information

```
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials 
  - keyring: 
    - active_backends: 
      - macOS Keyring
      - PlaintextKeyring with no encyption v.1.0 at /Users/jwodder/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /Users/jwodder/.config/python_keyring/keyringrc.cfg
    - data_root: /Users/jwodder/.local/share/python_keyring
## datalad 
  - version: 0.16.4
## dependencies 
  - annexremote: 1.6.0
  - boto: 2.49.0
  - cmd:7z: 17.04
  - cmd:annex: 10.20220624
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.36.1
  - cmd:system-git: 2.36.1
  - cmd:system-ssh: 8.1p1
  - humanize: 4.1.0
  - iso8601: 1.0.2
  - keyring: 23.5.1
  - keyrings.alt: 4.1.0
  - msgpack: 1.0.4
  - platformdirs: 2.5.2
  - requests: 2.27.1
## environment 
  - LANG: en_US.UTF-8
  - LC_ALL: en_US.UTF-8
  - PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/jwodder/bin:/Users/jwodder/.local/bin:/Users/jwodder/local/bin
## extensions 
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - FsEvents
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.30
    - DAV-1.3.4
    - feed-1.3.2.1
    - ghc-8.10.7
    - http-client-0.7.11
    - persistent-sqlite-2.13.1.0
    - torrent-10000.1.1
    - uuid-1.3.15
    - yesod-1.6.2
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: darwin x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
    - 9
    - 10
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20220624
## location 
  - path: /Users/jwodder/work
  - type: directory
## metadata_extractors 
  - annex: 
    - distribution: datalad 0.16.4
    - load_error: None
    - module: datalad.metadata.extractors.annex
  - audio: 
    - distribution: datalad 0.16.4
    - load_error: ModuleNotFoundError(No module named 'mutagen')
    - module: datalad.metadata.extractors.audio
  - datacite: 
    - distribution: datalad 0.16.4
    - load_error: None
    - module: datalad.metadata.extractors.datacite
  - datalad_core: 
    - distribution: datalad 0.16.4
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
  - datalad_rfc822: 
    - distribution: datalad 0.16.4
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
  - exif: 
    - distribution: datalad 0.16.4
    - load_error: ModuleNotFoundError(No module named 'exifread')
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage: 
    - distribution: datalad 0.16.4
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
  - image: 
    - distribution: datalad 0.16.4
    - load_error: ModuleNotFoundError(No module named 'PIL')
    - module: datalad.metadata.extractors.image
  - xmp: 
    - distribution: datalad 0.16.4
    - load_error: ModuleNotFoundError(No module named 'libxmp')
    - module: datalad.metadata.extractors.xmp
## metadata_indexers 
## python 
  - implementation: CPython
  - version: 3.9.13
## system 
  - distribution: darwin/20.6.0 11.6.6/x86_64
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 275
  - name: Darwin
  - release: 20.6.0
  - type: posix
  - version: Darwin Kernel Version 20.6.0: Tue Apr 19 21:04:45 PDT 2022; root:xnu-7195.141.29~1/RELEASE_X86_64
```
