### ISSUE TITLE
`datalad save` does not recognize change to uninstalled subdataset

### ISSUE THREAD

**Issue by jwodder** [datalad/datalad#7074]
### What is the problem?

If a dataset contains a subdataset `foo` that is not installed, and `foo` is updated "manually" (e.g., via `git update-index`), then `datalad save` will not recognize the change in `foo`.

### What steps will reproduce the problem?

```bash
#!/bin/bash
set -ex

datalad create foo
cd foo
touch file.txt
datalad save -m 'Init'
cd ..

datalad create super
cd super
datalad clone ../foo
datalad save -m 'Init'

rm -rf foo
mkdir foo
git status

printf '160000 commit 957e8407c5bffd46b741aeb96538f7205702c0d3\tfoo\n' | \
    git update-index --index-info
git status

datalad save -m 'Update foo'

git status
```

### DataLad information

```
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials 
  - keyring: 
    - active_backends: 
      - macOS Keyring
      - PlaintextKeyring with no encyption v.1.0 at /Users/jwodder/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /Users/jwodder/.config/python_keyring/keyringrc.cfg
    - data_root: /Users/jwodder/.local/share/python_keyring
## datalad 
  - version: 0.17.6
## dependencies 
  - annexremote: 1.6.0
  - boto: 2.49.0
  - cmd:7z: 17.04
  - cmd:annex: 10.20221003
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.38.0
  - cmd:ssh: 8.1p1
  - cmd:system-git: 2.38.0
  - cmd:system-ssh: 8.1p1
  - humanize: 4.4.0
  - iso8601: 1.1.0
  - keyring: 23.9.3
  - keyrings.alt: 4.2.0
  - msgpack: 1.0.4
  - platformdirs: 2.5.2
  - requests: 2.28.1
## environment 
  - LANG: en_US.UTF-8
  - LC_ALL: en_US.UTF-8
  - PATH: /usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Library/TeX/texbin:/opt/X11/bin:/Library/Apple/usr/bin:/Users/jwodder/bin:/Users/jwodder/.local/bin:/Users/jwodder/.cargo/bin:/Users/jwodder/local/bin
## extensions 
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - FsEvents
    - TorrentParser
    - MagicMime
    - Benchmark
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.30
    - DAV-1.3.4
    - feed-1.3.2.1
    - ghc-8.10.7
    - http-client-0.7.13.1
    - persistent-sqlite-2.13.1.0
    - torrent-10000.1.1
    - uuid-1.3.15
    - yesod-1.6.2.1
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: darwin x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
    - 9
    - 10
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20221003
## location 
  - path: /Users/jwodder/work
  - type: directory
## metadata_extractors 
  - annex: 
    - distribution: datalad 0.17.6
    - load_error: None
    - module: datalad.metadata.extractors.annex
  - audio: 
    - distribution: datalad 0.17.6
    - load_error: ModuleNotFoundError(No module named 'mutagen')
    - module: datalad.metadata.extractors.audio
  - datacite: 
    - distribution: datalad 0.17.6
    - load_error: None
    - module: datalad.metadata.extractors.datacite
  - datalad_core: 
    - distribution: datalad 0.17.6
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
  - datalad_rfc822: 
    - distribution: datalad 0.17.6
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
  - exif: 
    - distribution: datalad 0.17.6
    - load_error: ModuleNotFoundError(No module named 'exifread')
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage: 
    - distribution: datalad 0.17.6
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
  - image: 
    - distribution: datalad 0.17.6
    - load_error: ModuleNotFoundError(No module named 'PIL')
    - module: datalad.metadata.extractors.image
  - xmp: 
    - distribution: datalad 0.17.6
    - load_error: ModuleNotFoundError(No module named 'libxmp')
    - module: datalad.metadata.extractors.xmp
## metadata_indexers 
## python 
  - implementation: CPython
  - version: 3.10.7
## system 
  - distribution: darwin/20.6.0 11.6.8/x86_64
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - filesystem: 
    - CWD: 
      - path: /Users/jwodder/work
    - HOME: 
      - path: /Users/jwodder
    - TMP: 
      - path: /var/folders/l7/wrkq93d133d8zpn36fmqrq0r0000gn/T
  - max_path_length: 275
  - name: Darwin
  - release: 20.6.0
  - type: posix
  - version: Darwin Kernel Version 20.6.0: Tue Jun 21 20:50:28 PDT 2022; root:xnu-7195.141.32~1/RELEASE_X86_64
Hint: install psutil to get filesystem information
```
