### ISSUE TITLE
unable to push to origin due to lost connection

### ISSUE THREAD

**Issue by just-meng** [datalad/datalad#7241]
### What is the problem?

I have a gin repo hosting a large dataset (452G). It has been a while since my last push (due to wifi issues) and the accumulated changes are likely of big size. Anyway, I tried many times to push the dataset, and mostly would get an error message as below. Since it usually takes multiple days to push data anyway, I never knew if it was due to actual connection issue (wifi, bc ethernet doesn't work due to institutional data protection measures). But just now I was sitting in front of the PC and there was no wifi problem. The transfer still failed. I also did  `rm -rf .git/annex/transfer/*` before. 

```
USER@DESKTOP-FKUFN1U MINGW64 /d/Meng_Psychedelics/03_data/02_preprocessed_data/011_preliminary_psychedelics_suite2p (adjusted/master(unlocked))
$ rm -rf .git/annex/transfer/*

USER@DESKTOP-FKUFN1U MINGW64 /d/Meng_Psychedelics/03_data/02_preprocessed_data/011_preliminary_psychedelics_suite2p (adjusted/master(unlocked))
$ datalad push --to origin
[INFO] Determine push target
[INFO] Push refspecs
[INFO] Transfer data
        CommandError: '"git" "-c" "diff.ignoreSubmodules=none" "annex" "copy" "--batch" "-z" "--to" "origin" "--fast" "--json" "--json-error-messages" "--json-progress" "-c" "annex.dotfiles=true"' failed with exitcode 1 under D:\Meng_Psychedelics\03_data\02_preprocessed_data\011_preliminary_psychedelics_suite2p [info keys: stdout_json]
> to origin...
  Lost connection (fd:12: hGetChar: end of file)
  Transfer failed
  Lost connection (fd:4: hGetChar: end of file)
  Transfer failed
  This could have failed because --fast is enabled.
>  to origin...
  Lost connection (fd:10: hGetChar: end of file)
  Transfer failed
  Lost connection (fd:4: hGetChar: end of file)
  Transfer failed
  This could have failed because --fast is enabled.
>  to origin...
  Lost connection (fd:9: hPutBuf: resource vanished (Broken pipe))
  Transfer failed
  Lost connection (fd:3: hPutBuf: resource vanished (Broken pipe))
  Transfer failed
  Lost connection (fd:3: hPutBuf: resource vanished (Broken pipe))
  Transfer failed
  This could have failed because --fast is enabled.
Connection to gin.g-node.org closed by remote host.
CommandError: '"C:\WINDOWS\System32\OpenSSH\ssh.exe" "git@gin.g-node.org" "git-annex-shell 'p2pstdio' '/jwu/ds_preliminary_psychedelics_suite2p.git' 'e0747b29-2b27-40f2-bc2d-45e1b35185d8' --uuid 1360954f-2322-4c13-ba22-76239fc417eb"' failed with exitcode 4294967295
git-annex: transfer already in progress, or unable to take transfer lock
git-annex-shell: p2pstdio: 1 failed
CommandError: '"C:\WINDOWS\System32\OpenSSH\ssh.exe" "git@gin.g-node.org" "git-annex-shell 'p2pstdio' '/jwu/ds_preliminary_psychedelics_suite2p.git' 'e0747b29-2b27-40f2-bc2d-45e1b35185d8' --uuid 1360954f-2322-4c13-ba22-76239fc417eb"' failed with exitcode 1
Connection to gin.g-node.org closed by remote host.
CommandError: '"C:\WINDOWS\System32\OpenSSH\ssh.exe" "git@gin.g-node.org" "git-annex-shell 'p2pstdio' '/jwu/ds_preliminary_psychedelics_suite2p.git' 'e0747b29-2b27-40f2-bc2d-45e1b35185d8' --uuid 1360954f-2322-4c13-ba22-76239fc417eb"' failed with exitcode 4294967295
git-annex: transfer already in progress, or unable to take transfer lock
git-annex-shell: p2pstdio: 1 failed
CommandError: '"C:\WINDOWS\System32\OpenSSH\ssh.exe" "git@gin.g-node.org" "git-annex-shell 'p2pstdio' '/jwu/ds_preliminary_psychedelics_suite2p.git' 'e0747b29-2b27-40f2-bc2d-45e1b35185d8' --uuid 1360954f-2322-4c13-ba22-76239fc417eb"' failed with exitcode 1
client_loop: send disconnect: Connection reset
CommandError: '"C:\WINDOWS\System32\OpenSSH\ssh.exe" "git@gin.g-node.org" "git-annex-shell 'p2pstdio' '/jwu/ds_preliminary_psychedelics_suite2p.git' 'e0747b29-2b27-40f2-bc2d-45e1b35185d8' --uuid 1360954f-2322-4c13-ba22-76239fc417eb"' failed with exitcode 255
git-annex: transfer already in progress, or unable to take transfer lock
git-annex-shell: p2pstdio: 1 failed
CommandError: '"C:\WINDOWS\System32\OpenSSH\ssh.exe" "git@gin.g-node.org" "git-annex-shell 'p2pstdio' '/jwu/ds_preliminary_psychedelics_suite2p.git' 'e0747b29-2b27-40f2-bc2d-45e1b35185d8' --uuid 1360954f-2322-4c13-ba22-76239fc417eb"' failed with exitcode 1
git-annex: transfer already in progress, or unable to take transfer lock
git-annex-shell: p2pstdio: 1 failed
CommandError: '"C:\WINDOWS\System32\OpenSSH\ssh.exe" "git@gin.g-node.org" "git-annex-shell 'p2pstdio' '/jwu/ds_preliminary_psychedelics_suite2p.git' 'e0747b29-2b27-40f2-bc2d-45e1b35185d8' --uuid 1360954f-2322-4c13-ba22-76239fc417eb"' failed with exitcode 1
copy: 3 failed
```

### DataLad information

```
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials
  - keyring:
    - active_backends:
      - Windows WinVaultKeyring
      - Windows RegistryKeyring
      - EncryptedKeyring with not defined v.1.0 at C:\Users\USER\AppData\Local\Python Keyring\wincrypto_pass.cfg
      - PlaintextKeyring with no encyption v.1.0 at C:\Users\USER\AppData\Local\Python Keyring\keyring_pass.cfg
    - config_file: C:\Users\USER\.config\python_keyring\keyringrc.cfg
    - data_root: C:\Users\USER\AppData\Local\Python Keyring
## datalad
  - version: 0.17.2
## dataset
  - branches:
    - adjusted/main(unlocked)@18e6e85
    - git-annex@dfa443d
    - main@4e9117c
    - synced/main@4e9117c
  - id: None
  - metadata: <SENSITIVE, report disabled by configuration>
  - path: D:\Meng_Psychedelics
  - repo: AnnexRepo
## dependencies
  - annexremote: 1.6.0
  - boto: 2.49.0
  - cmd:annex: 8.20211117-gc3af94eff
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.37.2.windows.2
  - cmd:ssh: 8.1p1
  - cmd:system-git: 2.37.2.windows.2
  - cmd:system-ssh: 9.0p1
  - humanize: 4.3.0
  - iso8601: 1.0.2
  - keyring: 23.4.0
  - keyrings.alt: 4.1.1
  - msgpack: 1.0.3
  - platformdirs: 2.5.2
  - requests: 2.28.1
## environment
  - LC_CTYPE: en_US.UTF-8
  - PATH: C:\Users\USER\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\local\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\usr\bin;C:\Program Files\Git\mingw64\bin;C:\Program Files\Git\usr\bin;C:\Users\USER\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0;C:\WINDOWS\System32\OpenSSH;C:\Program Files\Git\cmd;C:\Users\USER\anaconda3;C:\Users\USER\anaconda3\Scripts;C:\Users\USER\anaconda3;C:\Users\USER\anaconda3\Scripts;C:\Program Files\Git\usr\bin\vendor_perl;C:\Program Files\Git\usr\bin\core_perl
## extensions
  - next:
    - description: What is next in DataLad
    - entrypoints:
      - datalad_next.create_sibling_webdav.CreateSiblingWebDAV:
        - class: CreateSiblingWebDAV
        - load_error: None
        - module: datalad_next.create_sibling_webdav
        - names:
          - create-sibling-webdav
      - datalad_next.credentials.Credentials:
        - class: Credentials
        - load_error: None
        - module: datalad_next.credentials
        - names:
    - load_error: None
    - module: datalad_next
    - version: 0.5.0
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - TorrentParser
    - MagicMime
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions:
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.29
    - DAV-1.3.4
    - feed-1.3.2.0
    - ghc-8.10.7
    - http-client-0.7.9
    - persistent-sqlite-2.13.0.3
    - torrent-10000.1.1
    - uuid-1.3.15
    - yesod-1.6.1.2
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 8
  - operating system: mingw32 x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions:
    - 8
  - upgrade supported from repository versions:
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
  - version: 8.20211117-gc3af94eff
## location
  - path: D:\Meng_Psychedelics
  - type: dataset
## metadata_extractors
  - annex:
    - distribution: datalad 0.17.2
    - load_error: None
    - module: datalad.metadata.extractors.annex
  - audio:
    - distribution: datalad 0.17.2
    - load_error: ModuleNotFoundError(No module named 'mutagen')
    - module: datalad.metadata.extractors.audio
  - datacite:
    - distribution: datalad 0.17.2
    - load_error: None
    - module: datalad.metadata.extractors.datacite
  - datalad_core:
    - distribution: datalad 0.17.2
    - load_error: None
    - module: datalad.metadata.extractors.datalad_core
  - datalad_rfc822:
    - distribution: datalad 0.17.2
    - load_error: None
    - module: datalad.metadata.extractors.datalad_rfc822
  - exif:
    - distribution: datalad 0.17.2
    - load_error: ModuleNotFoundError(No module named 'exifread')
    - module: datalad.metadata.extractors.exif
  - frictionless_datapackage:
    - distribution: datalad 0.17.2
    - load_error: None
    - module: datalad.metadata.extractors.frictionless_datapackage
  - image:
    - distribution: datalad 0.17.2
    - load_error: ImportError(DLL load failed while importing _imaging: The specified module could not be found.)
    - module: datalad.metadata.extractors.image
  - xmp:
    - distribution: datalad 0.17.2
    - load_error: ModuleNotFoundError(No module named 'libxmp')
    - module: datalad.metadata.extractors.xmp
## metadata_indexers
## python
  - implementation: CPython
  - version: 3.9.12
## system
  - distribution: mingw64_nt-10.0-19044/3.3.5  10/10.0.19044/SP0/Multiprocessor Free
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: cp1252
  - filesystem:
    - CWD:
      - max_pathlength: 260
      - mount_opts: rw,fixed
      - path: D:\Meng_Psychedelics
      - type: NTFS
    - HOME:
      - max_pathlength: 260
      - mount_opts: rw,fixed
      - path: C:\Users\USER
      - type: NTFS
    - TMP:
      - max_pathlength: 260
      - mount_opts: rw,fixed
      - path: C:\Users\USER\AppData\Local\Temp
      - type: NTFS
  - max_path_length: 259
  - name: Windows
  - release: 10
  - type: nt
  - version: 10.0.19044

```
