### ISSUE TITLE
Enhance appveyor to avoid needless CI runs

### ISSUE THREAD

**Issue by mih** [datalad/datalad#7324]
Something like this would be nice:

```yaml
# do not run the CI if only documentation changes were made
# documentation builds are tested elsewhere and cheaper
skip_commits:
  files:
    - docs/
    - changelog.d/
    - .github/
    - CHANGELOG.md
    - CITATION.cff
    - CONTRIBUTORS
    - LICENSE
    - Makefile
    - README.md
    - readthedocs.yml
```
