### ISSUE TITLE
I don't know (yet) what the exact thing I did was, but I ran into a possible data-loss situation

### ISSUE THREAD

**Issue by lukas-mertens** [datalad/datalad#7325]
### What is the problem?

Alright, first things first: I don't think I have any actual dataloss but I think I am near / something like this, combined with a git annex drop could possibly lead to dataloss, I don't know. Let's see what I did:

I have a nested dataset. The structure is something like the following. I will write datasets in capital-letters and normal directories in lowercase letters:

MAINDATASET
--A
--B
----subdir
------D
------E
------F
--C

Let's say dataset A, B, C and D already existed, everything is saved, working tree clean. Now I added datasets E and F using a little script I wrote for myself:

```sh
#!/bin/sh

# This script creates a new dataset in a given directory, and then creates a corresponding gitlab repository for it.
# Usage: create-gl-linked-datalad-dataset <dataset-name-1> <dataset-name-2> ... <dataset-name-n>

# This script assumes that python-gitlab is configured correctly (~/.python-gitlab.cfg) and that the user has write access to the gitlab server.

for dataset in "$@"
do
    datalad create --description "$dataset on lukmert-datalad" -c text2git $dataset
    cd $dataset
    datalad create-sibling-gitlab --site gitlab --project lukmert-datalad/$dataset --access ssh
    # Retrieve the remote URL for 'gitlab'
    url=$(git remote get-url gitlab)

    # Transform the URL to use git-remote-gcrypt
    new_url="gcrypt::$url#encrypted"

    # Set the new URL for 'gitlab'
    git remote remove gitlab
    git remote add gitlab $new_url
    git push
    cd ..
done
```

Everything fine so far, it creates normal datasets and creates a sibling for them. Now I added some files to dataset E. Then some time went by and I don't know exactly what I did inbetween, probably I started `git annex webapp` or `git annex assistant` in one of the datasets. Today I wanted to make sure that everything is saved properly in dataset E. So I ran git status which showed me all files with 'Typänderungen' (german for type changes) => it seems like the symlink type was changed or something like that. So I ran `datalad save` to clean everything up, just as usual. After doing that, git status now returns 'geändert' (engl. modified) for every file (or at least for a lot of them, I haven't checked each and everyone). The working tree is not clean, although a commit happened
![image](https://user-images.githubusercontent.com/10901304/225062244-4b749225-b26b-420d-9f63-bd5b45470ada.png). 
Running `git diff` returns something like the following:
![image](https://user-images.githubusercontent.com/10901304/225062887-db5574b3-d4c4-4c89-98d6-e76815da7102.png)

This is pretty interesting, it seems like the symlink of git annex changed and it is now pointing to the .git/annex/objects of dataset B. Now I tried to do a `git annex unannex` which restores the files perfectly fine => wow, lucky me, no dataloss (I have backups as well of course, but still).

Now I went up to dataset B and inspected things further. I had a look in the .gitmodules. It turns out: No dataset E or F in there, it seems like I didn't do a `datalad save` inside dataset B before so yeah, nothing too strange so far. But now I tried to do a `datalad save subdir/E` => doing a selective datalad save on the one dataset. Now it should, at least from what I learned, recognize the dataset as one and add it to the .gitmodules of dataset B. Interestingly, before I executed `datalad save` a `git status` showed the files inside dataset E as changed (so not the whole directory as untracked but individual files). After a `datalad save` nothing changes, it does a commit, says that it added quite a few files but they are still shown as "modified" in git status.

My idea: Probably I started the git annex assistant / webapp at some point in dataset B and it automatically added and committed my two datasets without recognizing that those are actually git submodules. This fucked things up. Could this be possible? Please help me to debug this further, as it can give insights on how not to use datalad, where it goes wrong and maybe we can do something to prevent that happening to other users. Additionally it would be great to fix my repository  of course :)

### DataLad information

```
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials
  - keyring:
    - active_backends:
      - macOS Keyring
      - PlaintextKeyring with no encyption v.1.0 at /Users/rooty/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /Users/rooty/.config/python_keyring/keyringrc.cfg
    - data_root: /Users/rooty/.local/share/python_keyring
## datalad
  - version: 0.18.2
## dataset
  - branches:
    - git-annex@962fd34
    - main@1f6f3ea
    - synced/git-annex@665fb88
    - synced/main@1f6f3ea
  - id: eca7f601-66c2-467f-a1e1-84b2e8f2dfa1
  - path: /Users/rooty/datalad/30_Resources
  - repo: AnnexRepo
## dependencies
  - annexremote: 1.6.0
  - boto: 2.49.0
  - cmd:7z: 17.04
  - cmd:annex: 10.20230227
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.38.4
  - cmd:ssh: 9.0p1
  - cmd:system-git: 2.38.4
  - cmd:system-ssh: 9.0p1
  - humanize: 4.6.0
  - iso8601: 1.1.0
  - keyring: 23.13.1
  - keyrings.alt: 4.2.0
  - msgpack: 1.0.4
  - platformdirs: 3.0.0
  - requests: 2.28.2
## environment
  - LANG: de_DE.UTF-8
  - LC_TERMINAL: iTerm2
  - LC_TERMINAL_VERSION: 3.4.19
  - PATH: <OmittedForPrivacyReasons>
  - PYTHONNOUSERSITE: true
## extensions
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - FsEvents
    - TorrentParser
    - MagicMime
    - Benchmark
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions:
    - aws-0.24
    - bloomfilter-2.0.1.0
    - cryptonite-0.30
    - DAV-1.3.4
    - feed-1.3.2.1
    - ghc-9.4.4
    - http-client-0.7.13.1
    - persistent-sqlite-2.13.1.1
    - torrent-10000.1.1
    - uuid-1.3.15
    - yesod-1.6.2.1
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 10
  - operating system: darwin aarch64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions:
    - 8
    - 9
    - 10
  - upgrade supported from repository versions:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20230227
## location
  - path: /Users/rooty/datalad/30_Resources
  - type: dataset
## python
  - implementation: CPython
  - version: 3.11.2
## system
  - distribution: darwin/22.3.0 13.2.1/arm64
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - filesystem:
    - CWD:
      - path: /Users/rooty/datalad/30_Resources
    - HOME:
      - path: /Users/rooty
    - TMP:
      - path: /var/folders/gk/gz41z9sn02d26_ltq5jxc0500000gn/T
  - max_path_length: 289
  - name: Darwin
  - release: 22.3.0
  - type: posix
  - version: Darwin Kernel Version 22.3.0: Mon Jan 30 20:38:37 PST 2023; root:xnu-8792.81.3~2/RELEASE_ARM64_T6000
```

### Have you had any success using DataLad before?

Yes, I used datalad for quite some time now
