### ISSUE TITLE
`datalad download-url` fails if server sends `content-encoding: gzip` header

### ISSUE THREAD

**Issue by xgui3783** [datalad/datalad#7433]
### What is the problem?

When attempting to download a url with `datalad download-url`, if server responds with [`Content-Encoding: gzip`](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Encoding) header, the command fails with 

```
[UnaccountedDownloadError(Downloaded size <gunzipped size> differs from originally announced <gzipped size>)] [Downloaded size <gunzipped size> differs from originally announced <gzipped size>]
```

### What steps will reproduce the problem?

```
datalad download-url https://neuroglancer.humanbrainproject.eu/precomputed/JuBrain/colin_auxmesh/meshes/JuBrain_Colin27_pial_left
```

### DataLad information

`datalad --version`

```
datalad 0.18.1
```

`datalad wtf`

```
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials 
  - keyring: 
    - active_backends: 
      - EncryptedKeyring with [PBKDF2] AES256.CFB v.1.0 at /home/xgui3783/.local/share/python_keyring/crypted_pass.cfg
      - PlaintextKeyring with no encyption v.1.0 at /home/xgui3783/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/xgui3783/.local/share/python_keyring/keyringrc.cfg
    - data_root: /home/xgui3783/.local/share/python_keyring
## datalad 
  - version: 0.18.1
## dataset 
  - branches: 
    - git-annex@b5c8613
    - master@9a0bf55
  - id: 9a5bb2ca-d43e-4fa9-b414-ddefe034c9c1
  - path: /home/xgui3783/dev/datalad/20230623-julichbrain300-colin-surface
  - repo: AnnexRepo
## dependencies 
  - annexremote: 1.4.3
  - appdirs: 1.4.3
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 10.20230126-1~ndall+1
  - cmd:bundled-git: 2.30.2
  - cmd:git: 2.30.2
  - cmd:ssh: 8.2p1
  - cmd:system-git: 2.25.1
  - cmd:system-ssh: 8.2p1
  - humanize: 1.0.0
  - iso8601: 0.1.12
  - keyring: 18.0.1
  - keyrings.alt: 3.4.0
  - msgpack: 0.6.2
  - requests: 2.22.0
## environment 
  - GIT_ASKPASS: /home/xgui3783/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/extensions/git/dist/askpass.sh
  - LANG: C.UTF-8
  - PATH: /home/xgui3783/dev/datalad/20230623-julichbrain300-colin-surface/venv/bin:/home/xgui3783/.vscode-server/bin/695af097c7bd098fbf017ce3ac85e09bbc5dda06/bin/remote-cli:/home/xgui3783/.nvm/versions/node/v16.18.1/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/usr/lib/wsl/lib:/mnt/c/WINDOWS/system32:/mnt/c/WINDOWS:/mnt/c/WINDOWS/System32/Wbem:/mnt/c/WINDOWS/System32/WindowsPowerShell/v1.0/:/mnt/c/WINDOWS/System32/OpenSSH/:/mnt/c/Program Files/Git/cmd:/Docker/host/bin:/mnt/c/Users/proto/AppData/Local/Programs/Python/Launcher/:/mnt/c/Users/proto/AppData/Local/Microsoft/WindowsApps:/mnt/c/Users/proto/AppData/Local/Programs/Microsoft VS Code/bin:/snap/bin:/usr/local/go/bin
## extensions 
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Benchmark
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.26
    - DAV-1.3.4
    - feed-1.3.0.1
    - ghc-8.8.4
    - http-client-0.6.4.1
    - persistent-sqlite-2.10.6.2
    - torrent-10000.1.1
    - uuid-1.3.13
    - yesod-1.6.1.0
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 10
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
    - 9
    - 10
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20230126-1~ndall+1
## location 
  - path: /home/xgui3783/dev/datalad/20230623-julichbrain300-colin-surface
  - type: dataset
## python 
  - implementation: CPython
  - version: 3.8.10
## system 
  - distribution: ubuntu/20.04/focal
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - filesystem: 
    - CWD: 
      - path: /home/xgui3783/dev/datalad/20230623-julichbrain300-colin-surface
    - HOME: 
      - path: /home/xgui3783
    - TMP: 
      - path: /tmp
  - max_path_length: 320
  - name: Linux
  - release: 5.15.90.1-microsoft-standard-WSL2
  - type: posix
  - version: #1 SMP Fri Jan 27 02:56:13 UTC 2023
Hint: install psutil to get filesystem information
```

### Additional context

I believe related to https://github.com/datalad/datalad/issues/4042

### Have you had any success using DataLad before?

Yes, but I would stil classify myself as a datanovice. Datalad has been invaluable tool to provide provenance to the produced data.

Most of the data repo are priviate unfortunately, but of the public, https://gin.g-node.org/FZJ-INM1-BDA/20210927-waxholm-v4
