### ISSUE TITLE
Issue with symlinked top level repository directory

### ISSUE THREAD

**Issue by TheChymera** [datalad/datalad#7438]
### What is the problem?

Datalad seems to get confused if the top level of the repository is navigated to via a symlink.

### What steps will reproduce the problem?

```console
[typhon]~/.local/share/datalad/vStr_phase_stim ❱ datalad get .
FileNotInRepositoryError:  [Path outside repository: /data/studies/manish/vStr_phase_stim]
[Errno None] : Path outside repository: /data/studies/manish/vStr_phase_stim: '/home/chymera/.local/share/datalad/vStr_phase_stim'
[typhon]~/.local/share/datalad/vStr_phase_stim ❱ pwd
/home/chymera/.local/share/datalad/vStr_phase_stim
[typhon]~/.local/share/datalad/vStr_phase_stim ❱ cd /data/studies/manish/vStr_phase_stim/
[typhon]/data/studies/manish/vStr_phase_stim ❱ datalad get .
[typhon]/data/studies/manish/vStr_phase_stim ❱
```

### DataLad information

<details>
<summary>WTF etc</summary> 

```
[typhon]~ ❱ datalad --version
datalad 0.18.3
[typhon]~ ❱ datalad wtf
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials
  - keyring:
    - active_backends:
      - SecretService Keyring
      - libsecret Keyring
      - EncryptedKeyring with [PBKDF2] AES256.CFB v.1.0 at /home/chymera/.local/share/python_keyring/crypted_pass.cfg
      - PlaintextKeyring with no encyption v.1.0 at /home/chymera/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/chymera/.config/python_keyring/keyringrc.cfg
    - data_root: /home/chymera/.local/share/python_keyring
## datalad
  - version: 0.18.3
## dependencies
  - annexremote: 1.6.0
  - appdirs: 1.4.4
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 10.20230126
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.39.2
  - cmd:ssh: 9.2p1
  - cmd:system-git: 2.39.2
  - cmd:system-ssh: 9.2p1
  - humanize: 0.0.0
  - iso8601: 1.0.2
  - keyring: 23.9.3
  - keyrings.alt: 4.2.0
  - msgpack: 1.0.3
  - requests: 2.28.1
## environment
  - LANG: en_US.UTF-8
  - PATH: /usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games:/usr/local/cuda/bin
## extensions
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Benchmark
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions:
    - aws-0.22.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.29
    - DAV-1.3.4
    - feed-1.3.2.1
    - ghc-9.0.2
    - http-client-0.7.13.1
    - persistent-sqlite-2.13.1.0
    - torrent-10000.1.1
    - uuid-1.3.15
    - yesod-1.6.2.1
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: linux x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions:
    - 8
    - 9
    - 10
  - upgrade supported from repository versions:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20230126
## location
  - path: /home/chymera
  - type: directory
## python
  - implementation: CPython
  - version: 3.11.2
## system
  - distribution: debian/12/bookworm
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - filesystem:
    - CWD:
      - max_pathlength: 4096
      - mount_opts: rw,noatime,compress=lzo,ssd,discard=async,space_cache=v2,subvolid=256,subvol=/home
      - path: /home/chymera
      - type: btrfs
    - HOME:
      - max_pathlength: 4096
      - mount_opts: rw,noatime,compress=lzo,ssd,discard=async,space_cache=v2,subvolid=256,subvol=/home
      - path: /home/chymera
      - type: btrfs
    - TMP:
      - max_pathlength: 4096
      - mount_opts: rw,relatime
      - path: /tmp
      - type: ext4
  - max_path_length: 269
  - name: Linux
  - release: 6.1.0-3-amd64
  - type: posix
  - version: #1 SMP PREEMPT_DYNAMIC Debian 6.1.8-1 (2023-01-29)
  ```

</details>

### Have you had any success using DataLad before?

yes
