### ISSUE TITLE
datalad.api.copy_file is quite slow?

### ISSUE THREAD

**Issue by JohannesWiesner** [datalad/datalad#7455]
### What is the problem?

I am basically following [this tutorial](https://handbook.datalad.org/en/latest/beyond_basics/101-149-copyfile.html) to first obtain a selection of around 700 HCP subjects as sub-datasets and then creating target datasets for these subjects with only a selection of files that I want (in order to not download lots of unnecessary stuff). I am currently helping myself with lots of nested for-loops to select and copy files but this takes very long (**even after this script has already been executed once**, thus getting a lot of _"copy_file, save (not needed)"_ messages). I wonder why? Am I not simply copying over symbolic links? Could I speed up `datalad.api.copy_file` by using the `specs_from` argument instead of nested for-loops?

### What steps will reproduce the problem?

```python
subjects = ['100206,'100307']

###############################################################################
## Get/Set source and target datasets #########################################
###############################################################################

# install and obtain the source dataset as a dataset object and create target dataset.
# Using dataset objects instead of paths will guarantee that datalad uses
# full paths behind the scenes without the user to specificy them.
if not os.path.isdir(src_dataset_path):
    install(source=src_url,path=src_dataset_path)
if not os.path.isdir(tgt_dataset_path):
    create(path=tgt_dataset_path)

src_dataset = Dataset(src_dataset_path)
tgt_dataset = Dataset(tgt_dataset_path)

###############################################################################
## Install subdatasets ########################################################
###############################################################################

print('Get src data')

# this takes a while when we first run this script, but runs quite fast when we execute the script another time
for subject in subjects:
    # get folders with functional data
    get(path=f"HCP1200/{subject}/MNINonLinear/Results/",dataset=src_dataset,get_data=False,recursive=True)

###############################################################################
## Create target dataset (THIS TAKES VERY LONG!!!!)
###############################################################################

print('Copy files from src to tgt')

# task-fMRI
tasks = ['EMOTION','GAMBLING','SOCIAL','WM','LANGUAGE','MOTOR','RELATIONAL']
encodings = ['LR','RL']

# TODO: This is very slow (even if this script already has been executed).
for task in tasks:
    for subject in subjects:
        for encoding in encodings:
            
            # specify source and target directories
            prefix = f"tfMRI_{task}_{encoding}"
            src_dir = f"{src_dataset.path}/HCP1200/{subject}/MNINonLinear/Results/{prefix}"
            
            if task == 'WM':
                tgt_dir = f"{tgt_dataset.path}/func/working_memory/{subject}/MNINonLinear/Results/{prefix}"
            else:
                tgt_dir = f"{tgt_dataset.path}/func/{task.lower()}/{subject}/MNINonLinear/Results/{prefix}"

            # specify the paths to the actual files that you want
            image_src = f"{src_dir}/{prefix}.nii.gz"
            movement_regressors_src = f"{src_dir}/Movement_Regressors.txt"
            movement_regressors_dt_src = f"{src_dir}/Movement_Regressors_dt.txt"
            evs_src = f"{src_dir}/EVs"
            
            # copy the files over to the destination dataset (equivalent to 
            # gits add and commit command)
            copy_file(path=image_src,target_dir=tgt_dir,dataset=tgt_dataset)
            copy_file(path=movement_regressors_src,target_dir=tgt_dir,dataset=tgt_dataset)
            copy_file(path=movement_regressors_dt_src,target_dir=tgt_dir,dataset=tgt_dataset)
            copy_file(path=evs_src,target_dir=tgt_dir,dataset=tgt_dataset,recursive=True)
```

### DataLad information

`datalad --version`:

datalad 0.18.1

`datalad wtf`:

```
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials
  - keyring:
    - active_backends:
      - SecretService Keyring
      - PlaintextKeyring with no encyption v.1.0 at /pandora/home/johannes.wiesner/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /pandora/home/johannes.wiesner/.config/python_keyring/keyringrc.cfg
    - data_root: /pandora/home/johannes.wiesner/.local/share/python_keyring
## datalad
  - version: 0.18.1
## dependencies
  - annexremote: 1.6.0
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 10.20230126-g36f5557
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.39.2
  - cmd:ssh: 9.1p1
  - cmd:system-git: 2.39.2
  - cmd:system-ssh: 9.1p1
  - humanize: 4.6.0
  - iso8601: 1.1.0
  - keyring: 23.13.1
  - keyrings.alt: 4.0.2
  - msgpack: 1.0.4
  - platformdirs: 3.0.0
  - requests: 2.28.2
## environment
  - LANG: C.UTF-8
  - PATH: /csp-tools/octave/7.3.0/bin:/csp-tools/anaconda3/envs/csp_wiesner_johannes/bin:/csp-tools/anaconda3/condabin:/sbin:/bin:/usr/bin:/usr/local/bin:/opt/thinlinc/bin
## extensions
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Benchmark
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions:
    - aws-0.22
    - bloomfilter-2.0.1.0
    - cryptonite-0.29
    - DAV-1.3.4
    - feed-1.3.2.0
    - ghc-8.10.7
    - http-client-0.7.9
    - persistent-sqlite-2.13.0.3
    - torrent-10000.1.1
    - uuid-1.3.15
    - yesod-1.6.1.2
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - operating system: linux x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions:
    - 8
    - 9
    - 10
  - upgrade supported from repository versions:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20230126-g36f5557
## location
  - path: /pandora/home/johannes.wiesner
  - type: directory
## python
  - implementation: CPython
  - version: 3.9.16
## system
  - distribution: ubuntu/18.04/bionic
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - filesystem:
    - CWD:
      - max_pathlength: 4096
      - mount_opts: rw,relatime,errors=remount-ro,data=ordered
      - path: /pandora/home/johannes.wiesner
      - type: ext4
    - HOME:
      - max_pathlength: 4096
      - mount_opts: rw,relatime,errors=remount-ro,data=ordered
      - path: /pandora/home/johannes.wiesner
      - type: ext4
    - TMP:
      - max_pathlength: 4096
      - mount_opts: rw,relatime,data=ordered
      - path: /tmp
      - type: ext4
  - max_path_length: 286
  - name: Linux
  - release: 4.15.0-197-generic
  - type: posix
```
