### ISSUE TITLE
Successful `datalad run` that fails at save should make it easy to complete the save

### ISSUE THREAD

**Issue by effigies** [datalad/datalad#7538]
### What is the problem?

Running a command with `datalad run`, if the run succeeds but the save fails, there is no message indicating how to finish saving after making manual fixes.

In this particular case, I ran `datalad run recon-all -sd subjects -s sub-01 -all -parallel -threads 10`, which produced some files that git annex failed to save (see [this git-annex bug](https://git-annex.branchable.com/bugs/Invalid_argument_saving_FreeSurfer_file_on_NTFS/), if interested).

A nice follow-up message would be something like

```
[INFO  ] To resume the save without re-running, use the following command:
    datalad save ...
```

### What steps will reproduce the problem?

Via @yarikoptic, here is a MRE:

```console
❯ datalad run bash -c "touch 123; sudo chown root 123;"
[INFO   ] == Command start (output follows) ===== 
[sudo] password for yoh: 
[INFO   ] == Command exit (modification check follows) ===== 
run(ok): /tmp/testds (dataset) [bash -c 'touch 123; sudo chown root 123;...]
[WARNING] Received an exception CommandError(CommandError: 'git -c diff.ignoreSubmodules=none -c core.quotepath=false annex add --json --json-error-messages -c annex.dotfiles=true -- 123' failed with exitcode 1 under /tmp/testds [info keys: stdout_json]
>123: setFileMode: permission denied (Operation not permitted) [err: 'add: 1 failed']). Canceling not-yet running jobs and waiting for completion of running. You can force earlier forceful exit by Ctrl-C. 
[INFO   ] Canceled 0 out of 0 jobs. 0 left running. 
Total: 0.00 datasets [00:00, ? datasets/s]CommandError: 'git -c diff.ignoreSubmodules=none -c core.quotepath=false annex add --json --json-error-messages -c annex.dotfiles=true -- 123' failed with exitcode 1 under /tmp/testds [info keys: stdout_json]
>123: setFileMode: permission denied (Operation not permitted)
add: 1 failed
```

### DataLad information

```
# WTF                                                          
## configuration <SENSITIVE, report disabled by configuration>
## credentials                                                 
  - keyring:        
    - active_backends: 
      - SecretService Keyring                                  
      - PlaintextKeyring with no encyption v.1.0 at /home/chris/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/chris/.config/python_keyring/keyringrc.cfg
    - data_root: /home/chris/.local/share/python_keyring
## datalad                                                     
  - version: 0.19.3
## dataset                                                     
  - branches:                 
    - git-annex@eb539b8                                        
  - id: None                                                   
  - path: /data/nipreps-data/test        
  - repo: AnnexRepo
## dependencies            
  - annexremote: 1.6.0                                         
  - boto: 2.49.0         
  - cmd:annex: 10.20230408-g5b1e8ba77
  - cmd:bundled-git: 2.40.1
  - cmd:git: 2.40.1
  - cmd:ssh: 8.9p1      
  - cmd:system-git: 2.34.1
  - cmd:system-ssh: 8.9p1    
  - humanize: 4.7.0
  - iso8601: 2.0.0                                                                                                            
  - keyring: 24.2.0                                            
  - keyrings.alt: 5.0.0                                        
  - msgpack: 1.0.5
  - platformdirs: 3.10.0
  - requests: 2.31.0
## environment 
  - LANG: en_US.UTF-8
  - PATH: /home/chris/node_modules/.bin:/home/chris/.yarn/bin:/home/chris/.local/bin:/usr/local/freesurfer/7.4.1/bin:/usr/loca
l/freesurfer/7.4.1/fsfast/bin:/usr/local/freesurfer/7.4.1/tktools:/usr/local/freesurfer/7.4.1/mni/bin:/usr/local/ants/2.4.2/bi
n:/usr/local/ants/2.4.2/bin:/home/chris/mambaforge/envs/default/bin:/home/chris/mambaforge/condabin:/home/chris/.nvm/versions/
node/v16.15.0/bin:/home/chris/node_modules/.bin:/home/chris/.yarn/bin:/home/chris/.local/bin:/usr/local/freesurfer/7.4.1/bin:/
usr/local/freesurfer/7.4.1/fsfast/bin:/usr/local/freesurfer/7.4.1/tktools:/usr/local/freesurfer/7.4.1/mni/bin:/usr/local/ants/
2.4.2/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin:/home/chris/abin:
/home/chris/abin
## extensions 
  - next: 
    - description: What is next in DataLad
    - entrypoints: 
      - datalad_next.commands.create_sibling_webdav.CreateSiblingWebDAV: 
        - class: CreateSiblingWebDAV
        - module: datalad_next.commands.create_sibling_webdav
        - names: 
          - create-sibling-webdav
      - datalad_next.commands.credentials.Credentials: 
        - class: Credentials
        - module: datalad_next.commands.credentials
        - names: 
      - datalad_next.commands.download.Download: 
        - class: Download
        - module: datalad_next.commands.download
        - names: 
          - download
      - datalad_next.commands.ls_file_collection.LsFileCollection: 
        - class: LsFileCollection
        - module: datalad_next.commands.ls_file_collection
        - names: 
          - ls-file-collection
      - datalad_next.commands.tree.TreeCommand: 
        - class: TreeCommand
        - module: datalad_next.commands.tree
        - names: 
          - tree
    - module: datalad_next
    - version: 1.0.2
  - osf: 
    - description: DataLad extension for OSF support
    - entrypoints: 
      - datalad_osf.create_sibling_osf.CreateSiblingOSF: 
        - class: CreateSiblingOSF
        - module: datalad_osf.create_sibling_osf
        - names: 
          - create-sibling-osf
          - create_sibling_osf
      - datalad_osf.credentials.OSFCredentials: 
        - class: OSFCredentials 
        - module: datalad_osf.credentials
        - names: 
          - osf-credentials
          - osf_credentials
    - module: datalad_osf
    - version: 0.3.0
## git-annex                                                                                                         [75/1256]
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Benchmark
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.29
    - DAV-1.3.4
    - feed-1.3.2.1
    - ghc-9.0.2
    - http-client-0.7.13.1
    - persistent-sqlite-2.13.1.0
    - torrent-10000.1.1
    - uuid-1.3.15
    - yesod-1.6.2.1
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 10
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
    - 9
    - 10
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20230408-g5b1e8ba77
## location 
  - path: /data/nipreps-data/test
  - type: dataset
## metadata.extractors 
## metadata.filters 
## metadata.indexers 
## python 
  - implementation: CPython
  - version: 3.11.4
## system 
  - distribution: ubuntu/22.04/jammy
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - filesystem: 
    - CWD: 
      - max_pathlength: 4096
      - mount_opts: rw,nosuid,nodev,relatime,user_id=0,group_id=0,default_permissions,allow_other,blksize=4096
      - path: /data/nipreps-data/test
      - type: fuseblk
    - HOME: 
      - max_pathlength: 4096
      - mount_opts: rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota
      - path: /home/chris
      - type: xfs
    - TMP: 
      - max_pathlength: 4096
      - mount_opts: rw,relatime,attr2,inode64,logbufs=8,logbsize=32k,noquota
      - path: /tmp
      - type: xfs
  - max_path_length: 279
  - name: Linux
  - release: 6.2.0-37-generic
  - type: posix
  - version: #38~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Thu Nov  2 18:01:13 UTC 2
```

### Have you had any success using DataLad before?

Yes!
