### ISSUE TITLE
`log_progress` does not log when a new RIA store is created

### ISSUE THREAD

**Issue by mslw** [datalad/datalad#7602]
### What is the problem?

This is the output of `create-sibling-ria`:

```
❱ datalad create-sibling-ria -s ria-backup --alias dl-101 --new-store-ok "ria+file:///tmp/my-store"
[INFO   ] create siblings 'ria-backup' and 'ria-backup-storage' ...
[INFO   ] Fetching updates for Dataset(/tmp/foo)
update(ok): . (dataset)
update(ok): . (dataset)
[INFO   ] Configure additional publication dependency on "ria-backup-storage"
configure-sibling(ok): . (sibling)
create-sibling-ria(ok): /tmp/foo (dataset)
action summary:
  configure-sibling (ok: 1)
  create-sibling-ria (ok: 1)
  update (ok: 1)
0.00 [00:01, ?/s]
```

I think it is missing one message that used to be shown previously, `[INFO] Creating a new RIA store at /tmp/my-store` - see e.g. [handbook examples here](https://handbook.datalad.org/en/latest/beyond_basics/101-147-riastores.html#creating-or-publishing-to-ria-stores).

### DataLad information

<details><summary>datalad wtf</summary>

```
❱ datalad wtf
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials
  - keyring:
    - active_backends:
      - SecretService Keyring
      - PlaintextKeyring with no encyption v.1.0 at /home/mszczepanik/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/mszczepanik/.config/python_keyring/keyringrc.cfg
    - data_root: /home/mszczepanik/.local/share/python_keyring
## datalad
  - version: 1.0.2+19.g06d64fbbc.dirty
## dataset
  - branches:
    - git-annex@7f983ff
    - main@6219901
  - id: 0aa093f2-2a54-4dcf-9843-aae9fe285ce6
  - path: /tmp/foo
  - repo: AnnexRepo
## dependencies
  - annexremote: 1.6.5
  - boto: 2.49.0
  - cmd:7z: 16.02
  - cmd:annex: 10.20230126
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.39.2
  - cmd:ssh: 9.2p1
  - cmd:system-git: 2.39.2
  - cmd:system-ssh: 9.2p1
  - humanize: 4.9.0
  - iso8601: 2.1.0
  - keyring: 25.2.1
  - keyrings.alt: 5.0.1
  - msgpack: 1.0.8
  - platformdirs: 4.2.2
  - requests: 2.32.1
## environment
  - LANG: en_US.UTF-8
  - LANGUAGE: en_US.UTF-8
  - LC_ALL: en_US.UTF-8
  - LC_CTYPE: en_US.UTF-8
  - PATH: /home/mszczepanik/.virtualenvs/tmp-face51b411acf7d/bin:/home/mszczepanik/.nvm/versions/node/v18.12.1/bin:/home/mszczepanik/.dotfiles/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin:/usr/local/games:/usr/games:/home/mszczepanik/.local/bin:/home/mszczepanik/.local/share/gem/ruby/2.7.0/bin:/home/mszczepanik/texlive/2022/bin/x86_64-linux:/home/mszczepanik/.cargo/bin
## extensions
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Benchmark
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions:
    - aws-0.22.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.29
    - DAV-1.3.4
    - feed-1.3.2.1
    - ghc-9.0.2
    - http-client-0.7.13.1
    - persistent-sqlite-2.13.1.0
    - torrent-10000.1.1
    - uuid-1.3.15
    - yesod-1.6.2.1
  - key/value backends:
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 10
  - operating system: linux x86_64
  - remote types:
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions:
    - 8
    - 9
    - 10
  - upgrade supported from repository versions:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20230126
## location
  - path: /tmp/foo
  - type: dataset
## metadata.extractors
## metadata.filters
## metadata.indexers
## python
  - implementation: CPython
  - version: 3.11.2
## system
  - distribution: debian/12/bookworm
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - filesystem:
    - CWD:
      - path: /tmp/foo
    - HOME:
      - path: /home/mszczepanik
    - TMP:
      - path: /tmp
  - max_path_length: 264
  - name: Linux
  - release: 6.1.0-20-amd64
  - type: posix
  - version: #1 SMP PREEMPT_DYNAMIC Debian 6.1.85-1 (2024-04-11)
Hint: install psutil to get filesystem information
```
</details>

### What I was able to find out

The (missing) message should be displayed via this call to log_progress, added in 1ea15cd:
https://github.com/datalad/datalad/blob/06d64fbbcf2d22fb4959a962d1f90b2b2f1e1d66/datalad/distributed/create_sibling_ria.py#L424-L427

The other two INFO messages (those which were shown) are displayed by direct calls to `lgr.info()`.

I was slightly surprised by the use of `log_progress` to display the single message (no updating etc.); although looking at the implementation of `log_progress` in [log.py](https://github.com/datalad/datalad/blob/06d64fbbcf2d22fb4959a962d1f90b2b2f1e1d66/datalad/log.py#L362), it is not clear to me whether that usage is wrong - it seems that when called that way (no kwargs), it *should* be equivalent to calling `lgr.info()`.

However, when replaced with a plain `lgr.info()`:

``` diff
@@ -421,10 +421,7 @@ class CreateSiblingRia(Interface):
                 yield res
                 return
 
-        log_progress(
-            lgr.info, 'create-sibling-ria',
-            'Creating a new RIA store at %s', local_base_path,
-        )
+        lgr.info('Creating a new RIA store at %s', local_base_path)
         create_store(io, local_base_path, '1')
 
         yield from _create_sibling_ria(

```

all info messages are produced:

```
❱ datalad create-sibling-ria -s ria-backup2 --alias dl-101 --new-store-ok "ria+file:///tmp/my-store2"
[INFO   ] Creating a new RIA store at /tmp/my-store2
[INFO   ] create siblings 'ria-backup2' and 'ria-backup2-storage' ...
[INFO   ] Fetching updates for Dataset(/tmp/foo)
update(ok): . (dataset)
update(ok): . (dataset)
[INFO   ] Configure additional publication dependency on "ria-backup2-storage"
configure-sibling(ok): . (sibling)
create-sibling-ria(ok): /tmp/foo (dataset)
action summary:
 (...)
```

### Additional information

Noticed while debugging Appveyor errors (which may, in the end, be unrelated) in datalad-handbook/book/pull/1223

### What confuses me

Looking at maint, the code in `log.py` has not been changed in two years, and the ria code for almost a year. Has the first INFO message been gone for so long? Has it ever been present? I believe it was there until fairly recently, but it's just my memory plus the Handbook run records. Now I can't roll back DataLad version to make it pop up. Is it just me?

Is it an isolated instance, or a sign of problems with logging?

Was there a reason for calling `log_progress()` instead of `lgr.info()`? Is `log_progress` meant to be used like that?
