### ISSUE TITLE
Config setting `datalad.get.subdataset-source-candidate-<name>` cannot deal with RIA store

### ISSUE THREAD

**Issue by mlell** [datalad/datalad#7631]
### What is the problem?

I would like to have a .gitmodules file which is just 

```
[submodule "subA"]
path=subA
datalad-id=XXXXX-XXXXX-XXXX...
```

And then globally set an environment variable which has the RIA store with all the working group's data sets. The reason is that if I write `url=` or `datalad-url=` into the `gitmodules` file, I freeze information which should not be frozen. The path of the central storage might change and then I cannot use the old url just because I check out an old version. 

However, I get the error message:

`Could not resolve hostname ria: Name or service not known`

### What steps will reproduce the problem?

```
# According to `datalad configuration --help`, I can craft an environment variable for the config item 
# "datalad.get.subdataset-source-candidate-mystore" like this
export DATALAD_GET_SUBDATASET__SOURCE__CANDIDATE__MYSTORE="ria:///filer/path/to/datasets-ria"

# Now download all subdatasets
$ datalad get -r -R1 .
ssh: Could not resolve hostname ria: Name or service not known
ssh: Could not resolve hostname ria: Name or service not known
Installing (1 failed): 0.00 [00:00, ?/s]install(error): /path/to/superdataset/subA (dataset) [Failed to clone
 from any candidate source URL. Encountered errors per each url were:
- (.... unrelated URLs that are tried and fail according to the algorithm explain in `datalad get --help` ....)
- ria:///filer/path/to/datasets-ria
  ConnectionOpenFailedError: 'ssh -fN -o ControlMaster=auto -o ControlPersist=15m -o ControlPath=/home/USER/.cache/datalad/sockets/85b756ac ria' failed with exitcode 
255 [Failed to open SSH connection (could not start ControlMaster process)]]
```

### DataLad information

git-annex version: 10.20230926-g44a7b4c9734adfda5912dd82c1aa97c615689f57

```
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials 
  - keyring: 
    - active_backends: 
      - SecretService Keyring
      - PlaintextKeyring with no encyption v.1.0 at /home/lell/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/lell/.config/python_keyring/keyringrc.cfg
    - data_root: /home/lell/.local/share/python_keyring
## datalad 
  - version: 0.19.3
## dataset 
  - branches: 
    - git-annex@780ccc5
    - lell@aa06085
    - master@067d83d
    - synced/lell@5e796c6
  - id: 575642b2-c0f7-4425-b426-fb4a0099d81e
  - path: /qg-10/data/AGR-QG/lell/BigData/collect/220830_impute
  - repo: AnnexRepo
## dependencies 
  - annexremote: 1.6.0
  - boto: 2.49.0
  - cmd:annex: 10.20230926-g44a7b4c9734adfda5912dd82c1aa97c615689f57
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.40.1
  - cmd:ssh: 8.7p1
  - cmd:system-git: 2.40.1
  - cmd:system-ssh: 8.7p1
  - humanize: 3.14.0
  - iso8601: 1.1.0
  - keyring: 23.4.1
  - keyrings.alt: 4.1.0
  - msgpack: 1.0.5
  - platformdirs: 3.2.0
  - requests: 2.27.1
## environment 
  - GIT_ANNEX_APP_BASE: /qg-10/data/AGR-QG/public/git-annex.testing
  - GIT_ANNEX_DIR: /qg-10/data/AGR-QG/public/git-annex.testing
  - GIT_ANNEX_LD_LIBRARY_PATH: /qg-10/data/AGR-QG/public/git-annex.testing//lib/x86_64-linux-gnu:
  - GIT_ANNEX_STANDLONE_ENV: PATH GCONV_PATH GIT_EXEC_PATH GIT_TEMPLATE_DIR MANPATH LOCPATH
  - GIT_BRANCH: lell
  - GIT_EXEC_PATH: /qg-10/data/AGR-QG/public/git-annex.testing/git-core
  - GIT_TEMPLATE_DIR: /qg-10/data/AGR-QG/public/git-annex.testing/templates
  - LANG: en_US.UTF-8
  - PATH: /qg-10/data/AGR-QG/public/datalad.testing/venv/bin:/qg-10/data/AGR-QG/public/git-annex.testing/bin:/qg-10/data/AGR-QG/lell/.bin:/home/lell/.local/bin:/qg-10
/data/AGR-QG/lell/.local/bin:/qg-10/data/AGR-QG/lell/.usr/bin:/filer/agruppen/qg/Computing-Cluster/scripts:/home/lell/perl5/bin:/usr/share/Modules/bin:/usr/local/bin:
/usr/bin:/usr/local/sbin:/usr/sbin:/usr/local/bin:/usr/local/bin:/qg-10/data/AGR-QG/public/git-annex.testing/extra:/usr/local/bin:/usr/local/bin
## extensions 
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Benchmark
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22.1
    - bloomfilter-2.0.1.0
    - crypton-0.33
    - DAV-1.3.4
    - feed-1.3.2.1
    - ghc-9.0.2
    - http-client-0.7.13.1
    - persistent-sqlite-2.13.1.0
    - torrent-10000.1.1
    - uuid-1.3.15
    - yesod-1.6.2.1
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - X*
  - local repository version: 10
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - hook
    - external
  - supported repository versions: 
    - 8
    - 9
    - 10
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20230926-g44a7b4c9734adfda5912dd82c1aa97c615689f57
## location 
  - path: /qg-10/data/AGR-QG/lell/BigData/collect/220830_impute
  - type: dataset
## metadata.extractors 
## metadata.filters 
## metadata.indexers 
## python 
  - implementation: CPython
  - version: 3.9.18
## system 
  - distribution: rocky/9.4/Blue Onyx
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - filesystem: 
    - CWD: 
      - path: /qg-10/data/AGR-QG/lell/BigData/collect/220830_impute
    - HOME: 
      - path: /home/lell
    - TMP: 
      - path: /tmp
  - max_path_length: 309
  - name: Linux
  - release: 5.14.0-427.20.1.el9_4.x86_64
  - type: posix
  - version: #1 SMP PREEMPT_DYNAMIC Fri Jun 7 14:51:39 UTC 2024
```
