### ISSUE TITLE
Fail to access object from local object storage via download-url

### ISSUE THREAD

**Issue by ddeepwell** [datalad/datalad#7632]
### Description

Datalad doesn't seem to be able to authenticate correctly to a local object storage. I am able to interact with the store via tools like s3cmd but cannot run datalad commands such as `datalad download-url`.

Here is the output from running `datalad download-url`:
```
$ datalad download-url "http://cephtest2:9020/annexscratch/file1.sh"
[INFO   ] Downloading 'http://cephtest2:9020/annexscratch/file1.sh' into '/home/david.deepwell/ecs-test/' 
Access to http://cephtest2:9020/annexscratch/file1.sh has failed.
Would you like to setup a new provider configuration to access url? (choices: [yes], no):

New provider name
Unique name to identify 'provider' for http://cephtest2:9020/annexscratch/file1.sh [cephtest2]: 

New provider regular expression
A (Python) regular expression to specify for which URLs this provider should be used [http://cephtest2:9020/annexscratch/file1\.sh]: 

Authentication type
What authentication type to use (choices: aws-s3, bearer_token, bearer_token_anon, html_form, http_auth, http_basic_auth, http_digest_auth, http_token, loris-token, nda-s3, none, xnat): aws-s3

Credential
What type of credential should be used? (choices: [aws-s3], git, loris-token, nda-s3, token, user_password): 

Save provider configuration file
Following configuration will be written to /home/david.deepwell/.config/datalad/providers/cephtest2.cfg:
# Provider configuration file created to initially access
# http://cephtest2:9020/annexscratch/file1.sh

[provider:cephtest2]
url_re = http://cephtest2:9020/annexscratch/file1\.sh
authentication_type = aws-s3
# Note that you might need to specify additional fields specific to the
# authenticator.  Fow now "look into the docs/source" of <class 'datalad.downloaders.s3.S3Authenticator'>
# aws-s3_
credential = cephtest2

[credential:cephtest2]
# If known, specify URL or email to how/where to request credentials
# url = ???
type = aws-s3
 (choices: [yes], no): 

[INFO   ] S3 session: Connecting to the bucket http://cephtest2:9020/annexscratch/file1.sh with authentication 
Access to http://cephtest2:9020/annexscratch/file1.sh has failed.
Would you like to setup a new provider configuration to access url? (choices: [yes], no): 

ERROR: 
Interrupted by user while doing magic: KeyboardInterrupt()
$
$
$ # Try command again
$ datalad download-url "http://cephtest2:9020/annexscratch/file1.sh"
[INFO   ] Downloading 'http://cephtest2:9020/annexscratch/file1.sh' into '/home/david.deepwell/ecs-test/' 
[INFO   ] S3 session: Connecting to the bucket http://cephtest2:9020/annexscratch/file1.sh with authentication 
Access to http://cephtest2:9020/annexscratch/file1.sh has failed.
Do you want to enter other credentials in case they were updated? (choices: yes, no): yes

You need to authenticate with 'cephtest2' credentials.
key_id: MYKEYMYKEYMYKEY

secret_id: 
[INFO   ] S3 session: Connecting to the bucket http://cephtest2:9020/annexscratch/file1.sh with authentication 
Access to http://cephtest2:9020/annexscratch/file1.sh has failed.
```

When using the `-l debug` flag, the only additional line that seems relevant is the following:
```
Access was denied: AccessDeniedError(Access to http://cephtest2:9020/annexscratch/file1.sh has failed: status code 403) 
```

Using the environment variables `AWS_ACCESS_KEY_ID` and `AWS_SECRET_ACCESS_KEY` also had fo effect.

Here is the contents of the `provider.cfg` file that was created. I have tried modifying the url_re to use a wildcard instead of the object name and to place the url in double quotes, all to no effect.
```
# Provider configuration file created to initially access
# http://cephtest2:9020/annexscratch/file1.sh

[provider:cephtest2]
url_re = http://cephtest2:9020/annexscratch/file1\.sh
authentication_type = aws-s3
# Note that you might need to specify additional fields specific to the
# authenticator.  Fow now "look into the docs/source" of <class 'datalad.downloaders.s3.S3Authenticator'>
# aws-s3_
credential = cephtest2

[credential:cephtest2]
# If known, specify URL or email to how/where to request credentials
# url = ???
type = aws-s3
```

Here is the result from `datalad wtf`:
```
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials 
  - keyring: 
    - active_backends: 
      - PlaintextKeyring with no encyption v.1.0 at /home/david.deepwell/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/david.deepwell/.config/python_keyring/keyringrc.cfg
    - data_root: /home/david.deepwell/.local/share/python_keyring
## datalad 
  - version: 1.1.1
## dependencies 
  - annexremote: 1.6.5
  - boto3: 1.34.141
  - cmd:7z: 16.02
  - cmd:annex: 10.20240701-g623f483a68736d95b158c763cff8b51f74fd5b05
  - cmd:bundled-git: 2.43.0
  - cmd:git: 2.43.0
  - cmd:ssh: 8.0p1
  - cmd:system-git: 2.39.3
  - cmd:system-ssh: 8.0p1
  - humanize: 4.10.0
  - iso8601: 2.1.0
  - keyring: 25.2.1
  - keyrings.alt: 5.0.1
  - msgpack: 1.0.8
  - platformdirs: 4.2.2
  - requests: 2.32.3
## environment 
  - LANG: en_CA.UTF-8
  - PATH: <removed>
## extensions 
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Benchmark
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.24.1
    - bloomfilter-2.0.1.2
    - crypton-0.33
    - DAV-1.3.4
    - feed-1.3.2.1
    - ghc-9.4.7
    - http-client-0.7.14
    - persistent-sqlite-2.13.2.0
    - torrent-10000.1.3
    - uuid-1.3.15
    - yesod-1.6.2.1
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - GITBUNDLE
    - GITMANIFEST
    - VURL
    - X*
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - rclone
    - hook
    - external
  - supported repository versions: 
    - 8
    - 9
    - 10
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20240701-g623f483a68736d95b158c763cff8b51f74fd5b05
## location 
  - path: /home/david.deepwell/ecs-test
  - type: directory
## metadata.extractors 
## metadata.filters 
## metadata.indexers 
## python 
  - implementation: CPython
  - version: 3.10.4
## system 
  - distribution: rocky/8.8/Green Obsidian
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - filesystem: 
    - CWD: 
      - path: /home/david.deepwell/ecs-test
    - HOME: 
      - path: /home/david.deepwell
    - TMP: 
      - path: /tmp
  - max_path_length: 285
  - name: Linux
  - release: 4.18.0-477.27.1.el8_8.x86_64
  - type: posix
  - version: #1 SMP Wed Sep 20 15:55:39 UTC 2023
```
