### ISSUE TITLE
Run with RIA-installed input bricks repository

### ISSUE THREAD

**Issue by Servinjesus1** [datalad/datalad#7639]
### What is the problem?

I cannot run a simple test when trying to use data imported from an RIA. I presume that during the `datalad get` stage `git-annex` is improperly used and sees the RIA's annex as non-standard. What's worse is that the run doesn't completely fail so what remains is a repository where *no* commands work, not even `git status`.

### What steps will reproduce the problem?

Here is what I ran:

```bash
# Setup

dl create project1
dl create project1/task1
cd project1/task1
mkdir in out                                                                                                                                                                                             git:(main|)
echo input1 > in/in1                                                                                                                                                                                     git:(main|)
dl save                                                                                                                                                                                               git:(main|…1

# First Task
dl run -m "Create Out1                                                                                                                                                                                   git:(main|)

Produce out1 from in1" -i in/in1 'echo "out: $(cat in/in1)" > out/out1'
git log --raw                                                                                                                                                                                            git:(main|)

# Upload to new RIA
dl create-sibling-ria -s origin ria+file:$(echo ~)/Downloads/TEMP/datalad_test/test1/ria --new-store-ok                                                                                                  git:(main|)
dl push --to origin                                                                                                                                                                                      git:(main|)


# Prepare Task2
dl create ../task2                                                                                                                                                                                       git:(main|)
cd ../task2                                                                                                                                                                                              git:(main|)
mkdir in out                                                                                                                                                                                             git:(main|)
dl install -s ../task1 in/task1                                                                                                                                                                          git:(main|)
dl save                                                                                                                                                                                               git:(main|…1

# Run Task2
dl run -m "Create Task2 from Task1

Use Task1 to get Task2 done" -i in/task1/out/out1 'echo "task2: $(cat in/task1/out/out1)" > out/out1'

# CommandError: 'git -c diff.ignoreSubmodules=none -c core.quotepath=false status --porcelain --untracked-files=normal --ignore-submodules=none' failed with exitcode 128
#   Remote origin-2: This repository is not initialized for use by git-annex, but /Users/coesite/Downloads/TEMP/datalad_test/test1/ria/a1f/02701-090b-4f35-9cef-c27f1e7f69aa/annex/objects/ exists, which indicates this repository was used by git-annex before, and may have lost its annex.uuid and annex.version configs. Either set back missing configs, or run git-annex init to initialize with a new uuid.
# fatal: protocol error: bad line length character:
# 001
# git-annex: git protocol error: unsupported protocol capabilities
# fatal: 'git status --porcelain=2' failed in submodule in/task1
```

### DataLad information

Truncated WTF:

```
# WTF
## datalad
  - version: 1.1.1
## dataset
  - branches:
    - git-annex@c90d93d
    - main@81ae766
  - id: e92ab6b8-09fc-4886-8684-d812967b2ba6
  - path: /Users/coesite/Downloads/TEMP/datalad_test/test1/project1/task2
  - repo: AnnexRepo
## dependencies
  - annexremote: 1.6.5
  - boto3: 1.34.138
  - cmd:7z: 17.05
  - cmd:annex: 10.20240701
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.45.2
  - cmd:ssh: 9.6p1
  - cmd:system-git: 2.45.2
  - cmd:system-ssh: 9.6p1
  - humanize: 4.9.0
  - iso8601: 2.1.0
  - keyring: 25.2.1
  - keyrings.alt: 5.0.1
  - msgpack: 1.0.8
  - platformdirs: 4.2.2
  - requests: 2.32.3
## git-annex
  - build flags:
    - Assistant
    - Webapp
    - Pairing
    - FsEvents
    - TorrentParser
    - MagicMime
    - Benchmark
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions:
    - aws-0.24.2
    - bloomfilter-2.0.1.2
    - crypton-1.0.0
    - DAV-1.3.4
    - feed-1.3.2.1
    - ghc-9.6.3
    - http-client-0.7.17
    - persistent-sqlite-2.13.3.0
    - torrent-10000.1.3
    - uuid-1.3.15
    - yesod-1.6.2.1
  - local repository version: 10
  - operating system: darwin aarch64
  - version: 10.20240701
## location
  - path: /Users/coesite/Downloads/TEMP/datalad_test/test1/project1/task2
  - type: dataset
## metadata.extractors
## metadata.filters
## metadata.indexers
## python
  - implementation: CPython
  - version: 3.11.9
## system
  - distribution: darwin/23.5.0 14.5/arm64
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - max_path_length: 319
  - name: Darwin
  - release: 23.5.0
  - type: posix
  - version: Darwin Kernel Version 23.5.0: Wed May  1 20:14:38 PDT 2024; root:xnu-10063.121.3~5/RELEASE_ARM64_T6020
Hint: install psutil to get filesystem information
```

### Additional context

I am trying to understand how one might reuse datasets in streamlined fashion, particularly when a project involves sequential use of inputs and outputs in order. To my understanding two perspectives help make this work:

1. Install then uninstall. Start your work by creating a dataset, installing what's required from past datasets, completing the work, then uninstalling the dataset from your project superdataset. Repeat for the next phase which will invariably install the subdatasets.
2. Become the Onion. What would be incorrect and redundant would be to have sequential datasets in a flat folder structure in your project dataset. While this is advantageous for viewing the progress from one phase to the next, it implies significant redundancy. This is because phase 2's dataset includes phase 1's (if as we assume here it depends on it), 3 includes 2 *and* 1, and so forth. Rather, it's better to work from a nested folder structure with stage 1 at the core and subsequent stages forming layers around this stage like the layers of an onion. This requires getting used to moving datasets around to accommodate new layers as they arise.

Ideally I want to fully minimize the number of copies of annexed files floating around during my work, as well as minimize the amount of git metadata. I get that annex ensures that git metadata remains lightweight, so it's not as big a deal that nesting causes clones to abound, but I can imagine my complex projects getting rather bloated by having many gits within gits within gits, regardless of what's in each git. Ultimately, however, I want datalad to help by offering complete provenance even across repositories: that way, even if I'm making something high-level like a presentation, I can always see exactly how everything from data figures to graphics were made with total freedom to remake these elements as necessary to fit the aesthetic or needs of this high-level task.

The problem right now is figuring out how to use an RIA as a remote to install, uninstall, push, and copy repos and storage files from and to, with minimal reliance on the hard parts like remembering repo UUID's in the RIA. I thought that `datalad install -s ../task1 in/task1` in `task2` - as in this example - would work, but something is failing.
