### ISSUE TITLE
test_save_dotfiles started to fail on Windows!

### ISSUE THREAD

**Issue by yarikoptic** [datalad/datalad#7657]
e.,g in https://ci.appveyor.com/project/mih/datalad/builds/50552167/job/vkvki9y0jj2l5ccp

```
FAILED ..\datalad\core\local\tests\test_save.py::test_save_dotfiles[False-None] - AssertionError: unexpected content of state "modified": [WindowsPath('C:/DLTMP/datalad_temp_tree_vex8wu7k/nodot')] != []
assert [WindowsPath(...8wu7k/nodot')] == []
  
  Left contains one more item: WindowsPath('C:/DLTMP/datalad_temp_tree_vex8wu7k/nodot')
  
  Full diff:
  - []
  + [
  +     WindowsPath('C:/DLTMP/datalad_temp_tree_vex8wu7k/nodot'),
  + ]
FAILED ..\datalad\core\local\tests\test_save.py::test_save_dotfiles[None-None] - AssertionError: unexpected content of state "modified": [WindowsPath('C:/DLTMP/datalad_temp_tree_uecovglb/nodot')] != []
assert [WindowsPath(...ovglb/nodot')] == []
  
  Left contains one more item: WindowsPath('C:/DLTMP/datalad_temp_tree_uecovglb/nodot')
  
  Full diff:
  - []
  + [
  +     WindowsPath('C:/DLTMP/datalad_temp_tree_uecovglb/nodot'),
  + ]
=========== 2 failed, 233 passed, 24 skipped in 1803.70s (0:30:03) ============
Command exited with code 1

```

started to happen just now

```
(git)smaug:/mnt/datasets/datalad/ci/logs/2024/09[master]git
$> git grep test_save_dotfiles | grep FAIL
06/pr/7654/44837f2/appveyor-9843-failed/1l6f9p9udkmkn8xj.txt:[00:27:56] [gw1] FAILED ..\datalad\core\local\tests\test_save.py::test_save_dotfiles[False-None] 
06/pr/7654/44837f2/appveyor-9843-failed/1l6f9p9udkmkn8xj.txt:[00:32:24] FAILED ..\datalad\core\local\tests\test_save.py::test_save_dotfiles[False-None] - AssertionError: unexpected content of state "modified": [WindowsPath('C:/DLTMP/datalad_temp_tree_ntkfoc7w/nodot')] != []
06/pr/7655/5da7e70/appveyor-9845-failed/vkvki9y0jj2l5ccp.txt:[00:27:16] [gw1] FAILED ..\datalad\core\local\tests\test_save.py::test_save_dotfiles[False-None] 
06/pr/7655/5da7e70/appveyor-9845-failed/vkvki9y0jj2l5ccp.txt:[00:27:37] [gw1] FAILED ..\datalad\core\local\tests\test_save.py::test_save_dotfiles[None-None] 
06/pr/7655/5da7e70/appveyor-9845-failed/vkvki9y0jj2l5ccp.txt:[00:32:17] FAILED ..\datalad\core\local\tests\test_save.py::test_save_dotfiles[False-None] - AssertionError: unexpected content of state "modified": [WindowsPath('C:/DLTMP/datalad_temp_tree_vex8wu7k/nodot')] != []
06/pr/7655/5da7e70/appveyor-9845-failed/vkvki9y0jj2l5ccp.txt:[00:32:17] FAILED ..\datalad\core\local\tests\test_save.py::test_save_dotfiles[None-None] - AssertionError: unexpected content of state "modified": [WindowsPath('C:/DLTMP/datalad_temp_tree_uecovglb/nodot')] != []
```

and even some prior runs today were ok

```
$> git grep test_save_dotfiles | grep PASS | grep 'appv.*\\tests' | tail
05/pr/7654/e533f87/appveyor-9842-success/qtnqiv3r8onk4at5.txt:[00:28:11] [gw1] PASSED ..\datalad\core\local\tests\test_save.py::test_save_dotfiles[None-nodot-subdir] 
06/pr/7654/44837f2/appveyor-9843-failed/1l6f9p9udkmkn8xj.txt:[00:27:34] [gw1] PASSED ..\datalad\core\local\tests\test_save.py::test_save_dotfiles[True-None] 
06/pr/7654/44837f2/appveyor-9843-failed/1l6f9p9udkmkn8xj.txt:[00:27:42] [gw1] PASSED ..\datalad\core\local\tests\test_save.py::test_save_dotfiles[True-nodot-subdir] 
06/pr/7654/44837f2/appveyor-9843-failed/1l6f9p9udkmkn8xj.txt:[00:28:05] [gw1] PASSED ..\datalad\core\local\tests\test_save.py::test_save_dotfiles[False-nodot-subdir] 
06/pr/7654/44837f2/appveyor-9843-failed/1l6f9p9udkmkn8xj.txt:[00:28:17] [gw1] PASSED ..\datalad\core\local\tests\test_save.py::test_save_dotfiles[None-None] 
06/pr/7654/44837f2/appveyor-9843-failed/1l6f9p9udkmkn8xj.txt:[00:28:23] [gw1] PASSED ..\datalad\core\local\tests\test_save.py::test_save_dotfiles[None-nodot-subdir] 
06/pr/7655/5da7e70/appveyor-9845-failed/vkvki9y0jj2l5ccp.txt:[00:26:55] [gw1] PASSED ..\datalad\core\local\tests\test_save.py::test_save_dotfiles[True-None] 
06/pr/7655/5da7e70/appveyor-9845-failed/vkvki9y0jj2l5ccp.txt:[00:27:03] [gw1] PASSED ..\datalad\core\local\tests\test_save.py::test_save_dotfiles[True-nodot-subdir] 
06/pr/7655/5da7e70/appveyor-9845-failed/vkvki9y0jj2l5ccp.txt:[00:27:25] [gw1] PASSED ..\datalad\core\local\tests\test_save.py::test_save_dotfiles[False-nodot-subdir] 
06/pr/7655/5da7e70/appveyor-9845-failed/vkvki9y0jj2l5ccp.txt:[00:27:47] [gw1] PASSED ..\datalad\core\local\tests\test_save.py::test_save_dotfiles[None-nodot-subdir] 
```

annex is the same ancient version:
```
$> grep cmd:annex 06/pr/7654/44837f2/appveyor-9843-failed/1l6f9p9udkmkn8xj.txt 06/pr/7655/5da7e70/appveyor-9845-failed/vkvki9y0jj2l5ccp.txt 
06/pr/7654/44837f2/appveyor-9843-failed/1l6f9p9udkmkn8xj.txt:[00:01:56]   - cmd:annex: 8.20211117-gc3af94eff
06/pr/7655/5da7e70/appveyor-9845-failed/vkvki9y0jj2l5ccp.txt:[00:02:12]   - cmd:annex: 8.20211117-gc3af94eff
```
so it is smth else.

**Comment by yarikoptic** [comment]
@mih @adswa any ideas on this? most likely some new `git` or `annex` behavior...

**Comment by adswa** [comment]
Sorry, I can't reproduce it on todays master with bleeding edge git version 2.46.2.windows.1 and bleeding edge git-annex version 10.20240831-gb3dc65615318ffed194dfb85e631482d4515a180.
 
 Here is the WTF
 ```
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials
  - keyring:
    - active_backends:
      - Windows WinVaultKeyring
      - Windows RegistryKeyring
      - EncryptedKeyring with not defined v.1.0 at C:\Users\mih\AppData\Local\Python Keyring\wincrypto_pass.cfg
      - PlaintextKeyring with no encyption v.1.0 at C:\Users\mih\AppData\Local\Python Keyring\keyring_pass.cfg
    - config_file: C:\Users\mih\AppData\Local\Python Keyring\keyringrc.cfg
    - data_root: C:\Users\mih\AppData\Local\Python Keyring
## datalad
  - version: 1.1.3+8.ga3ee97ee1
## dataset
  - branches:
    - master@a3ee97e
  - id: None
  - path: C:\Users\mih\repo\datalad
  - repo: GitRepo
## dependencies
  - annexremote: 1.6.0
  - boto3: 1.35.29
  - cmd:7z: 19.00
  - cmd:annex: 10.20240831-gb3dc65615318ffed194dfb85e631482d4515a180
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.46.2.windows.1
  - cmd:ssh: 8.6p1
  - cmd:system-git: 2.46.2.windows.1
  - cmd:system-ssh: 8.6p1
  - humanize: 4.2.3
  - iso8601: 1.0.2
  - keyring: 23.7.0
  - keyrings.alt: 4.1.1
  - msgpack: 1.0.4
  - platformdirs: 2.5.2
  - requests: 2.28.1
## environment
  - PATH: C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\Windows\System32;C:\Windows;C:\Windows\System32\wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\7-Zip;C:\Program Files (x86)\GnuPG\bin;C:\Program Files\Git\cmd;C:\Users\mih\AppData\Local\Programs\Python\Python39\Scripts\;C:\Users\mih\AppData\Local\Programs\Python\Python39\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\iCLS\;C:\Program Files\Intel\Intel(R) Management Engine Components\iCLS\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\OpenSSH\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\TortoiseGit\bin;C:\Users\mih\AppData\Local\Microsoft\WindowsApps;C:\Users\mih\Miniconda3\Library\mingw64\bin;C:\Program Files (x86)\Midnight Commander;C:\Program Files (x86)\7-Zip;C:\Users\mih\AppData\Local\Microsoft\WindowsApps;C:\Program Files\7-Zip;;C:\Users\mih\AppData\Local\Programs\Microsoft VS Code\bin
  - PYTHONPATH: C:\Users\mih\miniconda3\python
## extensions
## git-annex
  - version: 10.20240831-gb3dc65615318ffed194dfb85e631482d4515a180
build flags: Assistant Webapp Pairing TorrentParser MagicMime Servant Benchmark Feeds Testsuite S3 WebDAV
dependency versions: aws-0.24.2 bloomfilter-2.0.1.2 crypton-1.0.0 DAV-1.3.4 feed-1.3.2.1 ghc-9.8.2 http-client-0.7.17 persistent-sqlite-2.13.3.0 torrent-10000.1.3 uuid-1.3.16 yesod-1.6.2.1
key/value backends: SHA256E SHA256 SHA512E SHA512 SHA224E SHA224 SHA384E SHA384 SHA3_256E SHA3_256 SHA3_512E SHA3_512 SHA3_224E SHA3_224 SHA3_384E SHA3_384 SKEIN256E SKEIN256 SKEIN512E SKEIN512 BLAKE2B256E BLAKE2B256 BLAKE2B512E BLAKE2B512 BLAKE2B160E BLAKE2B160 BLAKE2B224E BLAKE2B224 BLAKE2B384E BLAKE2B384 BLAKE2BP512E BLAKE2BP512 BLAKE2S256E BLAKE2S256 BLAKE2S160E BLAKE2S160 BLAKE2S224E BLAKE2S224 BLAKE2SP256E BLAKE2SP256 BLAKE2SP224E BLAKE2SP224 SHA1E SHA1 MD5E MD5 WORM URL GITBUNDLE GITMANIFEST VURL X*
remote types: git gcrypt p2p S3 bup directory rsync web bittorrent webdav adb tahoe glacier ddar git-lfs httpalso borg rclone hook external
operating system: mingw32 x86_64
supported repository versions: 8 9 10
upgrade supported from repository versions: 2 3 4 5 6 7 8 9 10
## location
  - path: C:\Users\mih\repo\datalad
  - type: dataset
## metadata.extractors
## metadata.filters
## metadata.indexers
## python
  - implementation: CPython
  - version: 3.9.7
## system
  - distribution:   10/10.0.22631/SP0/Multiprocessor Free
  - encoding:
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: cp1252
  - filesystem:
    - CWD:
      - max_pathlength: 260
      - mount_opts: rw,fixed
      - path: C:\Users\mih\repo\datalad
      - type: NTFS
    - HOME:
      - max_pathlength: 260
      - mount_opts: rw,fixed
      - path: C:\Users\mih
      - type: NTFS
    - TMP:
      - max_pathlength: 260
      - mount_opts: rw,fixed
      - path: C:\Users\mih\AppData\Local\Temp
      - type: NTFS
  - max_path_length: 259
  - name: Windows
  - release: 10
  - type: nt
  - version: 10.0.22631
```


```
C:\Users\mih\repo\datalad>pytest -s -v datalad\core\local\tests\test_save.py::test_save_dotfiles
============================================ test session starts ============================================
platform win32 -- Python 3.9.7, pytest-7.2.2, pluggy-1.0.0 -- C:\Users\mih\AppData\Local\Programs\Python\Python39\python.exe
cachedir: .pytest_cache
rootdir: C:\Users\mih\repo\datalad, configfile: tox.ini
plugins: cov-4.0.0, fail-slow-0.3.0, xdist-3.2.0
collected 6 items

datalad/core/local/tests/test_save.py::test_save_dotfiles[True-None] create(ok): . (dataset)
add(ok): .dot (file)
add(ok): .dot-subdir\.dot (file)
add(ok): .dot-subdir\nodot (file)
add(ok): nodot (file)
add(ok): nodot-subdir\.dot (file)
add(ok): nodot-subdir\nodot (file)
save(ok): . (dataset)
action summary:
  add (ok: 6)
  save (ok: 1)
PASSED
datalad/core/local/tests/test_save.py::test_save_dotfiles[True-nodot-subdir] create(ok): . (dataset)
add(ok): nodot-subdir\.dot (file)
add(ok): nodot-subdir\nodot (file)
save(ok): . (dataset)
action summary:
  add (ok: 2)
  save (ok: 1)
PASSED
datalad/core/local/tests/test_save.py::test_save_dotfiles[False-None] create(ok): . (dataset)
add(ok): .dot (file)
add(ok): .dot-subdir\.dot (file)
add(ok): .dot-subdir\nodot (file)
add(ok): nodot (file)
add(ok): nodot-subdir\.dot (file)
add(ok): nodot-subdir\nodot (file)
save(ok): . (dataset)
action summary:
  add (ok: 6)
  save (ok: 1)
PASSED
datalad/core/local/tests/test_save.py::test_save_dotfiles[False-nodot-subdir] create(ok): . (dataset)
add(ok): nodot-subdir\.dot (file)
add(ok): nodot-subdir\nodot (file)
save(ok): . (dataset)
action summary:
  add (ok: 2)
  save (ok: 1)
PASSED
datalad/core/local/tests/test_save.py::test_save_dotfiles[None-None] create(ok): . (dataset)
add(ok): .dot (file)
add(ok): .dot-subdir\.dot (file)
add(ok): .dot-subdir\nodot (file)
add(ok): nodot (file)
add(ok): nodot-subdir\.dot (file)
add(ok): nodot-subdir\nodot (file)
save(ok): . (dataset)
action summary:
  add (ok: 6)
  save (ok: 1)
PASSED
datalad/core/local/tests/test_save.py::test_save_dotfiles[None-nodot-subdir] create(ok): . (dataset)
add(ok): nodot-subdir\.dot (file)
add(ok): nodot-subdir\nodot (file)
save(ok): . (dataset)
action summary:
  add (ok: 2)
  save (ok: 1)
PASSEDVersions: annexremote=1.6.0 boto3=1.35.29 cmd:7z=19.00 cmd:annex=10.20240831-gb3dc65615318ffed194dfb85e631482d4515a180 cmd:bundled-git=UNKNOWN cmd:git=2.46.2.windows.1 cmd:ssh=8.6p1 cmd:system-git=2.46.2.windows.1 cmd:system-ssh=8.6p1 datalad=1.1.3+8.ga3ee97ee1 humanize=4.2.3 iso8601=1.0.2 keyring=23.7.0 keyrings.alt=UNKNOWN msgpack=1.0.4 platformdirs=2.5.2 requests=2.28.1
Obscure filename: str=b";&%b5{}'.datc" repr=";&%b5{}'.datc"
Encodings: default='utf-8' filesystem='utf-8' locale.prefered='cp1252'
Environment: PATH='C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Windows\\System32;C:\\Windows;C:\\Windows\\System32\\wbem;C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\;C:\\Windows\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\7-Zip;C:\\Program Files (x86)\\GnuPG\\bin;C:\\Program Files\\Git\\cmd;C:\\Users\\mih\\AppData\\Local\\Programs\\Python\\Python39\\Scripts\\;C:\\Users\\mih\\AppData\\Local\\Programs\\Python\\Python39\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\iCLS\\;C:\\WINDOWS\\system32;C:\\WINDOWS;C:\\WINDOWS\\System32\\Wbem;C:\\WINDOWS\\System32\\WindowsPowerShell\\v1.0\\;C:\\WINDOWS\\System32\\OpenSSH\\;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL;C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\IPT;C:\\Program Files\\TortoiseGit\\bin;C:\\Users\\mih\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Users\\mih\\Miniconda3\\Library\\mingw64\\bin;C:\\Program Files (x86)\\Midnight Commander;C:\\Program Files (x86)\\7-Zip;C:\\Users\\mih\\AppData\\Local\\Microsoft\\WindowsApps;C:\\Program Files\\7-Zip;;C:\\Users\\mih\\AppData\\Local\\Programs\\Microsoft VS Code\\bin' PYTHONPATH='C:\\Users\\mih\\miniconda3\\python' GIT_CONFIG_PARAMETERS="'init.defaultBranch=dl-test-branch' 'clone.defaultRemoteName=dl-test-remote'" PYTHON_KEYRING_BACKEND='keyrings.alt.file.PlaintextKeyring' GIT_CONFIG_GLOBAL='C:\\Users\\mih\\AppData\\Local\\Temp\\datalad_temp_fqrep8ak\\.gitconfig' GIT_ASKPASS='true'


============================================= warnings summary ==============================================
..\..\AppData\Local\Programs\Python\Python39\lib\site-packages\boto\plugin.py:40
  C:\Users\mih\AppData\Local\Programs\Python\Python39\lib\site-packages\boto\plugin.py:40: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp

-- Docs: https://docs.pytest.org/en/stable/how-to/capture-warnings.html
======================================= 6 passed, 1 warning in 33.90s =======================================
```
