### ISSUE TITLE
Download lock when getting HCP-YA functional connectivity data

### ISSUE THREAD

**Issue by lilikapa** [datalad/datalad#7658]
### What is the problem?

I have independent jobs to clone and get data for single subjects of the [HCP-YA functional connectivity datalad dataset](https://github.com/datalad-datasets/hcp-functional-connectivity.git), process time-series, compute FC matrices and run regional connectivity-based parcellation, but some jobs are killed when trying to get or drop the datalad files. I have the impression that they are killed because a `/home/lpaas/.cache/datalad/locks/downloader-auth.lck` file is created and that continuously removing this file allows the jobs to proceed with the workflow.

For some subjects, I get the following error:
```
❱ cat rcbp_ldlpfc_sub-111211.3833493.17.err
[INFO] Attempting a clone into /tmp/lpaas_coil/hcp_fc 
[INFO] Attempting to clone from https://github.com/datalad-datasets/hcp-functional-connectivity.git to /tmp/lpaas_coil/hcp_fc 
[INFO] Start enumerating objects 
[INFO] Start counting objects 
[INFO] Start compressing objects 
[INFO] Start receiving objects 
[INFO] Start resolving deltas 
[INFO] Completed clone attempts for Dataset(/tmp/lpaas_coil/hcp_fc) 
[INFO] Remote origin not usable by git-annex; setting annex-ignore 
[INFO] https://github.com/datalad-datasets/hcp-functional-connectivity.git/config download failed: Not Found 
[INFO] Attempting a clone into /tmp/lpaas_coil/hcp_cat12_conf 
[INFO] Attempting to clone from file:///data/project/cat_preprocessed/dataladstore/alias/HCP-YA_conf to /tmp/lpaas_coil/hcp_cat12_conf 
[INFO] Completed clone attempts for Dataset(/tmp/lpaas_coil/hcp_cat12_conf) 
[INFO] Configure additional publication dependency on "inm7-storage" 
Traceback (most recent call last):
  File "/data/project/COIL/4_Analysis/cbp_dlpfc/code/S04_rcbp_individual_dlpfc.py", line 149, in <module>
    dataset.get(path2rsfmri)
  File "/home/lpaas/.pyenv/versions/rcbp_py311/lib/python3.11/site-packages/datalad/distribution/dataset.py", line 507, in apply_func
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/lpaas/.pyenv/versions/rcbp_py311/lib/python3.11/site-packages/datalad/interface/base.py", line 773, in eval_func
    return return_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lpaas/.pyenv/versions/rcbp_py311/lib/python3.11/site-packages/datalad/interface/base.py", line 763, in return_func
    results = list(results)
              ^^^^^^^^^^^^^
  File "/home/lpaas/.pyenv/versions/rcbp_py311/lib/python3.11/site-packages/datalad_next/patches/interface_utils.py", line 287, in _execute_command_
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'get',
  'annexkey': 'MD5E-s1000015413--bf74b606e776f6b5d9def1997354ec27.nii.gz',
  'error_message': 'Failed to download from any of 1 locations ["Unable to '
                   'acquire lock on '
                   "`b'/home/lpaas/.cache/datalad/locks/downloader-auth.lck'` "
                   'due to [Errno 116] Stale file handle"]',
  'path': '/tmp/lpaas_coil/hcp_fc/111211/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz',
  'refds': '/tmp/lpaas_coil/hcp_fc',
  'status': 'error',
  'type': 'file'}]
  4.92s user 5.44s system 64% cpu 16.079 total
  ```
  
  For some others:
  ```
  ❱ cat rcbp_ldlpfc_sub-144125.3833493.75.err
[INFO] Attempting a clone into /tmp/lpaas_coil/hcp_fc 
[INFO] Attempting to clone from https://github.com/datalad-datasets/hcp-functional-connectivity.git to /tmp/lpaas_coil/hcp_fc 
[INFO] Start enumerating objects 
[INFO] Start counting objects 
[INFO] Start compressing objects 
[INFO] Start receiving objects 
[INFO] Start resolving deltas 
[INFO] Completed clone attempts for Dataset(/tmp/lpaas_coil/hcp_fc) 
[INFO] Remote origin not usable by git-annex; setting annex-ignore 
[INFO] https://github.com/datalad-datasets/hcp-functional-connectivity.git/config download failed: Not Found 
[INFO] Attempting a clone into /tmp/lpaas_coil/hcp_cat12_conf 
[INFO] Attempting to clone from file:///data/project/cat_preprocessed/dataladstore/alias/HCP-YA_conf to /tmp/lpaas_coil/hcp_cat12_conf 
[INFO] Completed clone attempts for Dataset(/tmp/lpaas_coil/hcp_cat12_conf) 
[INFO] Configure additional publication dependency on "inm7-storage" 
Traceback (most recent call last):
  File "/data/project/COIL/4_Analysis/cbp_dlpfc/code/S04_rcbp_individual_dlpfc.py", line 269, in <module>
    dataset.drop(path2rsfmri)
  File "/home/lpaas/.pyenv/versions/rcbp_py311/lib/python3.11/site-packages/datalad/distribution/dataset.py", line 507, in apply_func
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/lpaas/.pyenv/versions/rcbp_py311/lib/python3.11/site-packages/datalad/interface/base.py", line 773, in eval_func
    return return_func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/lpaas/.pyenv/versions/rcbp_py311/lib/python3.11/site-packages/datalad/interface/base.py", line 763, in return_func
    results = list(results)
              ^^^^^^^^^^^^^
  File "/home/lpaas/.pyenv/versions/rcbp_py311/lib/python3.11/site-packages/datalad_next/patches/interface_utils.py", line 287, in _execute_command_
    raise IncompleteResultsError(
datalad.support.exceptions.IncompleteResultsError: Command did not complete successfully. 1 failed:
[{'action': 'drop',
  'annexkey': 'MD5E-s987209779--411af38d5f57f1d61fff6d9df1cd0818.nii.gz',
  'message': 'unsafe; Could only verify the existence of 0 out of 1 necessary '
             'copy; Unable to access these remotes: datalad; (Note that these '
             'git remotes have annex-ignore set: origin); (Use --reckless '
             'availability to override this check, or adjust numcopies.)',
  'path': '/tmp/lpaas_coil/hcp_fc/144125/MNINonLinear/Results/rfMRI_REST1_LR/rfMRI_REST1_LR_hp2000_clean.nii.gz',
  'refds': '/tmp/lpaas_coil/hcp_fc',
  'status': 'error',
  'type': 'file'}]
  161.51s user 19.54s system 40% cpu 7:24.91 total
  ```

### What steps will reproduce the problem?

`condor_submit S04_rcbp_individual.submit`

Content of `S04_rcbp_individual.submit` file:
```
# The environment
universe        = vanilla
getenv          = True

# Resources
request_cpus    = 1
request_memory  = 13G
request_disk    = 8G
requirements    = 

# Executable
initialdir      = /data/project/COIL/4_Analysis/cbp_dlpfc/code
executable      = $(initialdir)/rcbp_run_in_venv.sh
transfer_executable = False

# Job - arguments order: PYENV_NAME – PYTHON – SCRIPT – WD - OUTNAME – SUBJECTS – SEED - TARGET – k [min,max]
arguments       = rcbp_py311 python S04_rcbp_individual_dlpfc.py /data/project/COIL/4_Analysis/cbp_dlpfc ldlpfc_medfilt2_exclHO-PCGthr10_subsamp_remseed_5FWHM_bp01-08_confWMCSFcat12_k2-12 $(subject) seed.nii.gz target_subsamp_remseed.nii.gz [2,12]

# Logs
log             = $ENV(HOME)/htcondor/logs/rcbp_ldlpfc_sub-$(subject).$(Cluster).$(Process).log
output          = $ENV(HOME)/htcondor/logs/rcbp_ldlpfc_sub-$(subject).$(Cluster).$(Process).out
error           = $ENV(HOME)/htcondor/logs/rcbp_ldlpfc_sub-$(subject).$(Cluster).$(Process).err

queue subject from ../data/02_cbp/hcp_unrelated_subjects_391.csv
```

Contents of `rcbp_run_in_venv.sh`
```
#!/bin/bash

# Load necessary environment variables
source /home/lpaas/.zshrc

if [ $# -lt 2 ]; then
    echo "This script is meant to run a command within a Python environment."
    echo "It needs at least 2 parameters."
    echo "The first one must be the environment name."
    echo "The rest will be the command."
    exit 1
fi

# # Activate pyenv and the desired Python version
# export PYENV_ROOT="/home/lpaas/.pyenv"
# export PATH="$PYENV_ROOT/bin:$PATH"
# eval "$(pyenv init --path)"

# Activate the desired pyenv environment
env_name=$1     # Define name of pyenv with first argument
echo "Activating: ${env_name}"
pyenv activate "${env_name}"    # Activate the pyenv

# Move to working directory
workdir=$2      # Define working directory with second argument
echo "Moving to working directory: ${workdir}"
cd "${workdir}" || exit 1

# Shift the arguments to remove the first two
shift 2

# Run the rest of the arguments in the virtual environment
echo "Running... ${@} ...in virtual environment."
"$@"      # Execute the command
```

Contents of `S04_rcbp_individual_dlpfc.py`:
```
# Run rCBP at the individual-level using the left dlPFC
# Created by Lya Paas in May 2024
################################################################################

# %% ---------------------------------------------------------------------------
# Import libraries
import os
import sys
import ast
import logging
import datalad.api  #noqa

import numpy as np      # for data manipulation
import pandas as pd     # for data manipulation
import rcbp             # for rCBP functions
from rcbp.helpers import TimeSeriesHelper, ConnectivityHelper, ClusteringHelper

from sklearn.cluster import KMeans  # for individual-level clustering

from func.plot_FC_matrix import plot_FC_matrix

# %% ---------------------------------------------------------------------------
# Define variables

# Path to working directory (relative to CWD)
wd = sys.argv[1]           #arqv[0] is the name of script

# Path to results (relative to CWD), should exist already
results_dir = os.path.join(wd, 'results/02_rcbp')
outname = sys.argv[2]
outdir = os.path.join(results_dir, outname)

# Temporary directory to store intermediate results
tmp_dir = '/tmp/lpaas_coil/'  # for juseless
tmp_outdir = os.path.join(tmp_dir, outname)
# Create outdir folder
try:
    os.makedirs(tmp_outdir, mode=0o766, exist_ok=True)
    print(f"Temporary output directory '{tmp_outdir}' created successfully.")
except OSError:
    print(f"Temporary output directory '{tmp_outdir}' cannot be created.")

# Path to log directory
logdir = os.path.join(outdir, 'logs/individual')
os.makedirs(logdir, mode = 0o766, exist_ok=True)

# Path to subject list
subject = sys.argv[3]
# subject = '555348'      # '101309', '555348'

# Sessions
sessions = ['rfMRI_REST1_LR', 'rfMRI_REST1_RL']

# Creating subject-specfic output directory and temporary output directory
outdir_sub = os.path.join(outdir, f'individual/{subject}')
try:
    os.makedirs(outdir_sub, mode = 0o766, exist_ok = True)
    print("Subject directory '%s' created successfully." %outdir_sub)
except OSError as error:
    print("Subject directory '%s' can not be created." %outdir_sub)

tmp_outdir_sub = os.path.join(tmp_outdir, f'individual/{subject}')
try:
    os.makedirs(tmp_outdir_sub, mode=0o766, exist_ok=True)
    print(f"Temporary output directory '{tmp_outdir_sub}' created successfully.")
except OSError:
    print(f"Temporary output directory '{tmp_outdir_sub}' cannot be created.")

# Data dir to install dataset
hcp_dir = os.path.join(tmp_dir, 'hcp_fc') # tmp in juseless
hcp_conf_dir = os.path.join(tmp_dir, 'hcp_cat12_conf')  # tmp in juseless

# Masks
seedname = sys.argv[4]          # seed created with rCBP
targetname = sys.argv[5]        # target created with rCBP
# seedname = 'seed_medfilt.nii.gz'
# targetname = 'target_subsamp_remseed.nii.gz'

# rCBP parameters
# k: Number of clusters
k_str = sys.argv[6]                         # k is submitted as a string
k_v = ast.literal_eval(k_str)               # k is converted to a list
n_clusters = list(range(k_v[0], k_v[1]+1))    # create a list with the range of k
# n_clusters = [2, 12]

# %% ---------------------------------------------------------------------------
# Configure logging to direct log outputs to a text file
log_file_path = os.path.join(logdir, f'{subject}_logging_rcbp_clustering.txt')
logging.basicConfig(filename = log_file_path, level=logging.INFO, format='%(asctime)s %(message)s', datefmt='%d.%m.%Y %H:%M:%S')

# Initiate logging
logging.info(f'\n===== RUNNING INDIVIDUAL-LEVEL rCBP =====\n\n')

# Print package versions
logging.info(f'Datalad version: {datalad.__version__}')
logging.info(f'Numpy version: {np.__version__}')
logging.info(f'rCBP version: {rcbp.__version__}')

# Print variables
logging.info(f'\n\
WORKING dir:\n{wd}\n\
RESULTS dir:\n{results_dir}\n\
OUTPUT dir:\n{outname}\n\
Running SUBJECT: {subject}\n\
SUBJECT OUTPUT dir:\n{outdir_sub}\n\
HCP DATA dir:\n{hcp_dir}\n\
Seed: {seedname}\n\
Target: {targetname}\n\
Number of clusters: {n_clusters}\n\n')

# %% ---------------------------------------------------------------------------
# DATALAD: Install HCP datalad dataset
# Where the data is
dataset_url = 'https://github.com/datalad-datasets/hcp-functional-connectivity.git'
# dataset_url = 'https://hub.datalad.org/hcp-openaccess/hcp1200-functional-connectivity.git' # New datalad hub
dataset_conf_url = 'ria+file:///data/project/cat_preprocessed/dataladstore#~HCP-YA_conf'

# Clone dataset
logging.info(f'DATALAD: Cloning dataset in {hcp_dir}')
dataset = datalad.api.install(path = hcp_dir, source = dataset_url)
# This is a function that if you have the dataset and re-run the command, nothing will happen. 
# So, you can run it as many times as you want

# Clone dataset with confounds
logging.info(f'DATALAD: Cloning confounds in {hcp_conf_dir}')
dataset_conf = datalad.api.install(path = hcp_conf_dir, source = dataset_conf_url)

logging.info('Datasets cloned.\n\n')

# %% ---------------------------------------------------------------------------
# Loop per session: Get data, time series and connectivity helpers

sub_dir = os.path.join(hcp_dir, f'{subject}')

for ses in sessions:
    # Get rsfMRI: With datalad get (handbook)
    # Path to rsfMRI
    path2rsfmri = f'{sub_dir}/MNINonLinear/Results/{ses}/{ses}_hp2000_clean.nii.gz'

    logging.info(f'Getting rsfMRI {ses} for subject {subject}:\n{path2rsfmri}')
    dataset.get(path2rsfmri)
    logging.info(f'rsfMRI {ses} obtained.')

    # Get CAT12 confounds regressors (from FelixH)
    # Columns: ['GM', 'WM', 'CSF', 'GS', 'GM^2', 'WM^2', 'CSF^2', 'GS^2', 
    # 'RP.1', 'RP.2', 'RP.3', 'RP.4', 'RP.5', 'RP.6', 
    # 'RP^2.1', 'RP^2.2', 'RP^2.3', 'RP^2.4', 'RP^2.5', 'RP^2.6', 
    # 'DRP.1', 'DRP.2', 'DRP.3', 'DRP.4', 'DRP.5', 'DRP.6', 
    # 'DRP^2.1', 'DRP^2.2', 'DRP^2.3', 'DRP^2.4', 'DRP^2.5', 'DRP^2.6', 
    # 'WMPCA.1', 'WMPCA.2', 'WMPCA.3', 'WMPCA.4', 'WMPCA.5','WMPCA.6', 'WMPCA.7', 
    # 'CSFPCA.1', 'CSFPCA.2', 'CSFPCA.3', 'CSFPCA.4', 'CSFPCA.5', 'CSFPCA.6', 'CSFPCA.7', 
    # 'FD']
    mod_ses = ses.replace('_', '')
    path2conf = f'{hcp_conf_dir}/sub-{subject}/sub-{subject}_task-{mod_ses}hp2000clean_desc-confounds_timeseries.tsv'
    logging.info(f'Getting CAT12 confound regressors.')
    dataset_conf.get(path2conf)
    logging.info('Got.')

    # Read confounds as dataframe and convert into numpy array
    conf_names = ['WM', 'CSF']
    logging.info(f'Confounds: {conf_names}')
    conf = pd.read_csv(path2conf, sep='\t', usecols=conf_names)
    confounds = conf.values

    # %% ---------------------------------------------------------------------------
    # Step 2: Time-series preprocessing
            # Preprocesses your time-series data with various functions and masks your data 
            # so only relevant voxels are kept (this vastly reduces the size of the image).
            # Make sure to use the processed masks here!
    logging.info('RUNNING TimeSeriesHelper...')
    ts = TimeSeriesHelper(
        # smoothing_fwhm = None,
        smoothing_fwhm = 5,
        # bandpass = None,
        # tr_seconds = None)
        bandpass = (0.01, 0.08),
        tr_seconds = 0.72)
    logging.info(f'SETTINGS:\n{ts}')
    
    logging.info(f'Preprocessing:\n{path2rsfmri}')
    ts.run(
        time_series = path2rsfmri,
        seed = os.path.join(outdir, seedname), 
        target = os.path.join(outdir, targetname),
        confounds = confounds     # optional: (m_timepoints, n_regressors). Shouldn't contain header!
        )

    ts.save(path = tmp_outdir_sub,
            time_series = f'timeseries_{ses}.nii.gz')
    logging.info(f'TimeSeriesHelper DONE!!!\n\n')

    # %% ---------------------------------------------------------------------------
    # Step 3: Connectivity
            # Calculate the connectivity between the seed and target masks.
            # Make sure to use the preprocessed masks and time-series
    logging.info('RUNNING ConnectivityHelper...')
    conn = ConnectivityHelper(transforms = ['fisherz'],
                              pca_components = None)
    logging.info(f'SETTINGS:\n{conn}')

    ts_file = os.path.join(tmp_outdir_sub, f'timeseries_{ses}.nii.gz')

    logging.info(f'Computing connectivity for:\n{ts_file}')
    conn.run(time_series = ts_file,
             seed = os.path.join(outdir, seedname),
             target = os.path.join(outdir, targetname))
    
    conn.save(path = tmp_outdir_sub,
              connectivity=f'zFC_{ses}.npz')
    logging.info(f'ConnectivityHelper DONE!\n\n')

    # %% -----------------------------------------------------------------------
    # Drop datalad dataset (confounds from CAT12, FelixH)
    logging.info(f'Dropping datalad files for subject {subject}, session {ses}: \n{path2rsfmri} \n{path2conf}')
    dataset.drop(path2rsfmri)
    dataset_conf.drop(path2conf)
    logging.info(f'DROPPED.\n\n')

# %% ---------------------------------------------------------------------------
# Step 4: Merge multi-session connectivity matrices
        # Merge the connectivity matrices from multiple sessions
        # REMEMBER: If PCA transformation used, the connectivity matrices should be averaged first and then apply PCA
logging.info(f'MERGING connectivity matrices for sessions:\n{sessions}')

path2ses1 = os.path.join(tmp_outdir_sub, f'zFC_{sessions[0]}.npz')
path2ses2 = os.path.join(tmp_outdir_sub, f'zFC_{sessions[1]}.npz')

ses1 = np.load(path2ses1)
ses2 = np.load(path2ses2)

# Average the connectivity matrices
logging.info('Averaging connectivity matrices...')
conn = np.mean([ses1['arr_0'], ses2['arr_0']], axis=0)

# Save the merged connectivity matrix
conn_file = os.path.join(outdir_sub, f'zconnectivity.npz')
np.savez_compressed(conn_file, conn)
logging.info(f'Merging connectivity matrices DONE!\nSaved under:\n{outdir_sub}\n...as zconnectivity.npz\n\n')

# Plot the connectivity matrix
logging.info(f'PLOTTING connectivity matrix...')
plot_FC_matrix(npz_path = conn_file, subject = subject)

# %% ---------------------------------------------------------------------------
# Step 5: Clustering: Individual-level
        # Cluster the connectivity matrices
        # First, do `from sklearn.cluster import KMeans` first
        # Then `kmeans = KMeans(...)` to define the kmeans parameters (check website)
        # https://scikit-learn.org/stable/modules/generated/sklearn.cluster.KMeans.html
        # Make sure to use the preprocessed masks and connectivity matrices
logging.info(f'INDIVIDUAL-LEVEL CLUSTERING...')

for i in n_clusters:
    logging.info(f'RUNNING ClusteringHelper with k = {i}...')

    # Define kmeans paramaters (sklearn)
    kmeans = KMeans(n_clusters = i, 
                    init = 'k-means++',
                    n_init = 256,
                    max_iter = 10000,
                    random_state = 1)

    cluster = ClusteringHelper(algorithm = kmeans)
    logging.info(f'SETTINGS:\n{cluster}')

    logging.info(f'Connectivity matrix:\n{conn_file}')
    cluster.run(matrix = conn_file)
    cluster.save(labels = os.path.join(outdir_sub, f'{i}cluster_labels.npz'))
    logging.info(f'Cluster labels for k = {i} saved under:\n{outdir_sub}\n...as {i}cluster_labels.npz\n')

logging.info(f'Individual-level clustering DONE.\n\n')
# %% ---------------------------------------------------------------------------
# Removing files (timeseries and zFC) to save space
logging.info(f'REMOVING single-session timeseries and FC files to save space under:\n{outdir_sub}')
for ses in sessions:
    os.remove(os.path.join(tmp_outdir_sub, f'timeseries_{ses}.nii.gz'))
    os.remove(os.path.join(tmp_outdir_sub, f'zFC_{ses}.npz'))
os.remove(tmp_outdir_sub)
logging.info('Temporary files REMOVED.\n')

logging.info('===== INDIVIDUAL-LEVEL rCBP DONE!!!! =====\n\n')
```

### DataLad information

```
❱ datalad wtf                                                                                                                                                                                           2 !
# WTF
## configuration <SENSITIVE, report disabled by configuration>
## credentials 
  - keyring: 
    - active_backends: 
      - PlaintextKeyring with no encyption v.1.0 at /home/lpaas/.local/share/python_keyring/keyring_pass.cfg
    - config_file: /home/lpaas/.config/python_keyring/keyringrc.cfg
    - data_root: /home/lpaas/.local/share/python_keyring
## datalad 
  - version: 1.1.2
## dependencies 
  - annexremote: 1.6.5
  - boto3: 1.35.7
  - cmd:7z: 16.02
  - cmd:annex: 10.20240430
  - cmd:bundled-git: UNKNOWN
  - cmd:git: 2.39.2
  - cmd:ssh: 9.2p1
  - cmd:system-git: 2.39.2
  - cmd:system-ssh: 9.2p1
  - humanize: 4.9.0
  - iso8601: 2.1.0
  - keyring: 25.2.0
  - keyrings.alt: 5.0.1
  - msgpack: 1.0.8
  - platformdirs: 4.2.1
  - requests: 2.31.0
## environment 
  - LANG: en_US.UTF-8
  - LANGUAGE: en_US.UTF-8
  - LC_ALL: en_US.UTF-8
  - LC_CTYPE: en_US.UTF-8
  - PATH: /home/lpaas/.pyenv/versions/rcbp_py311/bin:/home/lpaas/.pyenv/libexec:/home/lpaas/.pyenv/plugins/python-build/bin:/home/lpaas/.pyenv/plugins/pyenv-virtualenv/bin:/home/lpaas/.pyenv/plugins/pyenv-update/bin:/home/lpaas/.pyenv/plugins/pyenv-doctor/bin:/home/lpaas/.pyenv/shims:/home/lpaas/.pyenv/bin:/home/lpaas/miniconda3/bin:/home/lpaas/miniconda3/condabin:/home/lpaas/.dotfiles/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/X11R6/bin:/usr/local/games:/usr/games
## extensions 
  - next: 
    - description: What is next in DataLad
    - entrypoints: 
      - datalad_next.commands.create_sibling_webdav.CreateSiblingWebDAV: 
        - class: CreateSiblingWebDAV
        - module: datalad_next.commands.create_sibling_webdav
        - names: 
          - create-sibling-webdav
      - datalad_next.commands.credentials.Credentials: 
        - class: Credentials
        - module: datalad_next.commands.credentials
        - names: 
      - datalad_next.commands.download.Download: 
        - class: Download
        - module: datalad_next.commands.download
        - names: 
          - download
      - datalad_next.commands.ls_file_collection.LsFileCollection: 
        - class: LsFileCollection
        - module: datalad_next.commands.ls_file_collection
        - names: 
          - ls-file-collection
      - datalad_next.commands.status.Status: 
        - class: Status
        - module: datalad_next.commands.status
        - names: 
          - next-status
          - next_status
      - datalad_next.commands.tree.TreeCommand: 
        - class: TreeCommand
        - module: datalad_next.commands.tree
        - names: 
          - tree
    - module: datalad_next
    - version: 1.3.0
## git-annex 
  - build flags: 
    - Assistant
    - Webapp
    - Pairing
    - Inotify
    - DBus
    - DesktopNotify
    - TorrentParser
    - MagicMime
    - Benchmark
    - Feeds
    - Testsuite
    - S3
    - WebDAV
  - dependency versions: 
    - aws-0.22.1
    - bloomfilter-2.0.1.0
    - cryptonite-0.29
    - DAV-1.3.4
    - feed-1.3.2.1
    - ghc-9.0.2
    - http-client-0.7.13.1
    - persistent-sqlite-2.13.1.0
    - torrent-10000.1.1
    - uuid-1.3.15
    - yesod-1.6.2.1
  - key/value backends: 
    - SHA256E
    - SHA256
    - SHA512E
    - SHA512
    - SHA224E
    - SHA224
    - SHA384E
    - SHA384
    - SHA3_256E
    - SHA3_256
    - SHA3_512E
    - SHA3_512
    - SHA3_224E
    - SHA3_224
    - SHA3_384E
    - SHA3_384
    - SKEIN256E
    - SKEIN256
    - SKEIN512E
    - SKEIN512
    - BLAKE2B256E
    - BLAKE2B256
    - BLAKE2B512E
    - BLAKE2B512
    - BLAKE2B160E
    - BLAKE2B160
    - BLAKE2B224E
    - BLAKE2B224
    - BLAKE2B384E
    - BLAKE2B384
    - BLAKE2BP512E
    - BLAKE2BP512
    - BLAKE2S256E
    - BLAKE2S256
    - BLAKE2S160E
    - BLAKE2S160
    - BLAKE2S224E
    - BLAKE2S224
    - BLAKE2SP256E
    - BLAKE2SP256
    - BLAKE2SP224E
    - BLAKE2SP224
    - SHA1E
    - SHA1
    - MD5E
    - MD5
    - WORM
    - URL
    - VURL
    - X*
  - operating system: linux x86_64
  - remote types: 
    - git
    - gcrypt
    - p2p
    - S3
    - bup
    - directory
    - rsync
    - web
    - bittorrent
    - webdav
    - adb
    - tahoe
    - glacier
    - ddar
    - git-lfs
    - httpalso
    - borg
    - rclone
    - hook
    - external
  - supported repository versions: 
    - 8
    - 9
    - 10
  - upgrade supported from repository versions: 
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 6
    - 7
    - 8
    - 9
    - 10
  - version: 10.20240430
## location 
  - path: /data/project/COIL/4_Analysis/cbp_dlpfc/code
  - type: directory
## metadata.extractors 
## metadata.filters 
## metadata.indexers 
## python 
  - implementation: CPython
  - version: 3.11.8
## system 
  - distribution: debian/12/bookworm
  - encoding: 
    - default: utf-8
    - filesystem: utf-8
    - locale.prefered: UTF-8
  - filesystem: 
    - CWD: 
      - path: /data/project/COIL/4_Analysis/cbp_dlpfc/code
    - HOME: 
      - path: /home/lpaas
    - TMP: 
      - path: /tmp
  - max_path_length: 300
  - name: Linux
  - release: 6.6.13+bpo-amd64
  - type: posix
  - version: #1 SMP PREEMPT_DYNAMIC Debian 6.6.13-1~bpo12+1 (2024-02-15)
```

### Have you had any success using DataLad before?

Yes, the datalad part for these jobs was working fine until two weeks ago.
